// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/plugin/runtime/v1/direct_plugin_runtime.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.plugin.runtime.v1;

/**
 * Protobuf type {@code cyrene.plugin.runtime.v1.DirectStreamItem}
 */
public final class DirectStreamItem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cyrene.plugin.runtime.v1.DirectStreamItem)
    DirectStreamItemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DirectStreamItem.newBuilder() to construct.
  private DirectStreamItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DirectStreamItem() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DirectStreamItem();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.cyrene.plugin.runtime.v1.DirectPluginRuntimeOuterClass.internal_static_cyrene_plugin_runtime_v1_DirectStreamItem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.cyrene.plugin.runtime.v1.DirectPluginRuntimeOuterClass.internal_static_cyrene_plugin_runtime_v1_DirectStreamItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.cyrene.plugin.runtime.v1.DirectStreamItem.class, io.cyrene.plugin.runtime.v1.DirectStreamItem.Builder.class);
  }

  private int eventCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object event_;
  public enum EventCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    PAYLOAD(1),
    ERROR(2),
    END(3),
    EVENT_NOT_SET(0);
    private final int value;
    private EventCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventCase valueOf(int value) {
      return forNumber(value);
    }

    public static EventCase forNumber(int value) {
      switch (value) {
        case 1: return PAYLOAD;
        case 2: return ERROR;
        case 3: return END;
        case 0: return EVENT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public EventCase
  getEventCase() {
    return EventCase.forNumber(
        eventCase_);
  }

  public static final int PAYLOAD_FIELD_NUMBER = 1;
  /**
   * <code>.cyrene.plugin.runtime.v1.DirectPayload payload = 1;</code>
   * @return Whether the payload field is set.
   */
  @java.lang.Override
  public boolean hasPayload() {
    return eventCase_ == 1;
  }
  /**
   * <code>.cyrene.plugin.runtime.v1.DirectPayload payload = 1;</code>
   * @return The payload.
   */
  @java.lang.Override
  public io.cyrene.plugin.runtime.v1.DirectPayload getPayload() {
    if (eventCase_ == 1) {
       return (io.cyrene.plugin.runtime.v1.DirectPayload) event_;
    }
    return io.cyrene.plugin.runtime.v1.DirectPayload.getDefaultInstance();
  }
  /**
   * <code>.cyrene.plugin.runtime.v1.DirectPayload payload = 1;</code>
   */
  @java.lang.Override
  public io.cyrene.plugin.runtime.v1.DirectPayloadOrBuilder getPayloadOrBuilder() {
    if (eventCase_ == 1) {
       return (io.cyrene.plugin.runtime.v1.DirectPayload) event_;
    }
    return io.cyrene.plugin.runtime.v1.DirectPayload.getDefaultInstance();
  }

  public static final int ERROR_FIELD_NUMBER = 2;
  /**
   * <code>.cyrene.plugin.runtime.v1.DirectInvocationError error = 2;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return eventCase_ == 2;
  }
  /**
   * <code>.cyrene.plugin.runtime.v1.DirectInvocationError error = 2;</code>
   * @return The error.
   */
  @java.lang.Override
  public io.cyrene.plugin.runtime.v1.DirectInvocationError getError() {
    if (eventCase_ == 2) {
       return (io.cyrene.plugin.runtime.v1.DirectInvocationError) event_;
    }
    return io.cyrene.plugin.runtime.v1.DirectInvocationError.getDefaultInstance();
  }
  /**
   * <code>.cyrene.plugin.runtime.v1.DirectInvocationError error = 2;</code>
   */
  @java.lang.Override
  public io.cyrene.plugin.runtime.v1.DirectInvocationErrorOrBuilder getErrorOrBuilder() {
    if (eventCase_ == 2) {
       return (io.cyrene.plugin.runtime.v1.DirectInvocationError) event_;
    }
    return io.cyrene.plugin.runtime.v1.DirectInvocationError.getDefaultInstance();
  }

  public static final int END_FIELD_NUMBER = 3;
  /**
   * <code>.cyrene.plugin.runtime.v1.DirectStreamEnd end = 3;</code>
   * @return Whether the end field is set.
   */
  @java.lang.Override
  public boolean hasEnd() {
    return eventCase_ == 3;
  }
  /**
   * <code>.cyrene.plugin.runtime.v1.DirectStreamEnd end = 3;</code>
   * @return The end.
   */
  @java.lang.Override
  public io.cyrene.plugin.runtime.v1.DirectStreamEnd getEnd() {
    if (eventCase_ == 3) {
       return (io.cyrene.plugin.runtime.v1.DirectStreamEnd) event_;
    }
    return io.cyrene.plugin.runtime.v1.DirectStreamEnd.getDefaultInstance();
  }
  /**
   * <code>.cyrene.plugin.runtime.v1.DirectStreamEnd end = 3;</code>
   */
  @java.lang.Override
  public io.cyrene.plugin.runtime.v1.DirectStreamEndOrBuilder getEndOrBuilder() {
    if (eventCase_ == 3) {
       return (io.cyrene.plugin.runtime.v1.DirectStreamEnd) event_;
    }
    return io.cyrene.plugin.runtime.v1.DirectStreamEnd.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventCase_ == 1) {
      output.writeMessage(1, (io.cyrene.plugin.runtime.v1.DirectPayload) event_);
    }
    if (eventCase_ == 2) {
      output.writeMessage(2, (io.cyrene.plugin.runtime.v1.DirectInvocationError) event_);
    }
    if (eventCase_ == 3) {
      output.writeMessage(3, (io.cyrene.plugin.runtime.v1.DirectStreamEnd) event_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (io.cyrene.plugin.runtime.v1.DirectPayload) event_);
    }
    if (eventCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (io.cyrene.plugin.runtime.v1.DirectInvocationError) event_);
    }
    if (eventCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (io.cyrene.plugin.runtime.v1.DirectStreamEnd) event_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.cyrene.plugin.runtime.v1.DirectStreamItem)) {
      return super.equals(obj);
    }
    io.cyrene.plugin.runtime.v1.DirectStreamItem other = (io.cyrene.plugin.runtime.v1.DirectStreamItem) obj;

    if (!getEventCase().equals(other.getEventCase())) return false;
    switch (eventCase_) {
      case 1:
        if (!getPayload()
            .equals(other.getPayload())) return false;
        break;
      case 2:
        if (!getError()
            .equals(other.getError())) return false;
        break;
      case 3:
        if (!getEnd()
            .equals(other.getEnd())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (eventCase_) {
      case 1:
        hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
        hash = (53 * hash) + getPayload().hashCode();
        break;
      case 2:
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
        break;
      case 3:
        hash = (37 * hash) + END_FIELD_NUMBER;
        hash = (53 * hash) + getEnd().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.cyrene.plugin.runtime.v1.DirectStreamItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.plugin.runtime.v1.DirectStreamItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.plugin.runtime.v1.DirectStreamItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.plugin.runtime.v1.DirectStreamItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.plugin.runtime.v1.DirectStreamItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.plugin.runtime.v1.DirectStreamItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.plugin.runtime.v1.DirectStreamItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.plugin.runtime.v1.DirectStreamItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.cyrene.plugin.runtime.v1.DirectStreamItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.cyrene.plugin.runtime.v1.DirectStreamItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.cyrene.plugin.runtime.v1.DirectStreamItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.plugin.runtime.v1.DirectStreamItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.cyrene.plugin.runtime.v1.DirectStreamItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cyrene.plugin.runtime.v1.DirectStreamItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cyrene.plugin.runtime.v1.DirectStreamItem)
      io.cyrene.plugin.runtime.v1.DirectStreamItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.cyrene.plugin.runtime.v1.DirectPluginRuntimeOuterClass.internal_static_cyrene_plugin_runtime_v1_DirectStreamItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.cyrene.plugin.runtime.v1.DirectPluginRuntimeOuterClass.internal_static_cyrene_plugin_runtime_v1_DirectStreamItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.cyrene.plugin.runtime.v1.DirectStreamItem.class, io.cyrene.plugin.runtime.v1.DirectStreamItem.Builder.class);
    }

    // Construct using io.cyrene.plugin.runtime.v1.DirectStreamItem.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (payloadBuilder_ != null) {
        payloadBuilder_.clear();
      }
      if (errorBuilder_ != null) {
        errorBuilder_.clear();
      }
      if (endBuilder_ != null) {
        endBuilder_.clear();
      }
      eventCase_ = 0;
      event_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.cyrene.plugin.runtime.v1.DirectPluginRuntimeOuterClass.internal_static_cyrene_plugin_runtime_v1_DirectStreamItem_descriptor;
    }

    @java.lang.Override
    public io.cyrene.plugin.runtime.v1.DirectStreamItem getDefaultInstanceForType() {
      return io.cyrene.plugin.runtime.v1.DirectStreamItem.getDefaultInstance();
    }

    @java.lang.Override
    public io.cyrene.plugin.runtime.v1.DirectStreamItem build() {
      io.cyrene.plugin.runtime.v1.DirectStreamItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.cyrene.plugin.runtime.v1.DirectStreamItem buildPartial() {
      io.cyrene.plugin.runtime.v1.DirectStreamItem result = new io.cyrene.plugin.runtime.v1.DirectStreamItem(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(io.cyrene.plugin.runtime.v1.DirectStreamItem result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(io.cyrene.plugin.runtime.v1.DirectStreamItem result) {
      result.eventCase_ = eventCase_;
      result.event_ = this.event_;
      if (eventCase_ == 1 &&
          payloadBuilder_ != null) {
        result.event_ = payloadBuilder_.build();
      }
      if (eventCase_ == 2 &&
          errorBuilder_ != null) {
        result.event_ = errorBuilder_.build();
      }
      if (eventCase_ == 3 &&
          endBuilder_ != null) {
        result.event_ = endBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.cyrene.plugin.runtime.v1.DirectStreamItem) {
        return mergeFrom((io.cyrene.plugin.runtime.v1.DirectStreamItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.cyrene.plugin.runtime.v1.DirectStreamItem other) {
      if (other == io.cyrene.plugin.runtime.v1.DirectStreamItem.getDefaultInstance()) return this;
      switch (other.getEventCase()) {
        case PAYLOAD: {
          mergePayload(other.getPayload());
          break;
        }
        case ERROR: {
          mergeError(other.getError());
          break;
        }
        case END: {
          mergeEnd(other.getEnd());
          break;
        }
        case EVENT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getPayloadFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getEndFieldBuilder().getBuilder(),
                  extensionRegistry);
              eventCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int eventCase_ = 0;
    private java.lang.Object event_;
    public EventCase
        getEventCase() {
      return EventCase.forNumber(
          eventCase_);
    }

    public Builder clearEvent() {
      eventCase_ = 0;
      event_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.plugin.runtime.v1.DirectPayload, io.cyrene.plugin.runtime.v1.DirectPayload.Builder, io.cyrene.plugin.runtime.v1.DirectPayloadOrBuilder> payloadBuilder_;
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectPayload payload = 1;</code>
     * @return Whether the payload field is set.
     */
    @java.lang.Override
    public boolean hasPayload() {
      return eventCase_ == 1;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectPayload payload = 1;</code>
     * @return The payload.
     */
    @java.lang.Override
    public io.cyrene.plugin.runtime.v1.DirectPayload getPayload() {
      if (payloadBuilder_ == null) {
        if (eventCase_ == 1) {
          return (io.cyrene.plugin.runtime.v1.DirectPayload) event_;
        }
        return io.cyrene.plugin.runtime.v1.DirectPayload.getDefaultInstance();
      } else {
        if (eventCase_ == 1) {
          return payloadBuilder_.getMessage();
        }
        return io.cyrene.plugin.runtime.v1.DirectPayload.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectPayload payload = 1;</code>
     */
    public Builder setPayload(io.cyrene.plugin.runtime.v1.DirectPayload value) {
      if (payloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        payloadBuilder_.setMessage(value);
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectPayload payload = 1;</code>
     */
    public Builder setPayload(
        io.cyrene.plugin.runtime.v1.DirectPayload.Builder builderForValue) {
      if (payloadBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        payloadBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectPayload payload = 1;</code>
     */
    public Builder mergePayload(io.cyrene.plugin.runtime.v1.DirectPayload value) {
      if (payloadBuilder_ == null) {
        if (eventCase_ == 1 &&
            event_ != io.cyrene.plugin.runtime.v1.DirectPayload.getDefaultInstance()) {
          event_ = io.cyrene.plugin.runtime.v1.DirectPayload.newBuilder((io.cyrene.plugin.runtime.v1.DirectPayload) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 1) {
          payloadBuilder_.mergeFrom(value);
        } else {
          payloadBuilder_.setMessage(value);
        }
      }
      eventCase_ = 1;
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectPayload payload = 1;</code>
     */
    public Builder clearPayload() {
      if (payloadBuilder_ == null) {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 1) {
          eventCase_ = 0;
          event_ = null;
        }
        payloadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectPayload payload = 1;</code>
     */
    public io.cyrene.plugin.runtime.v1.DirectPayload.Builder getPayloadBuilder() {
      return getPayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectPayload payload = 1;</code>
     */
    @java.lang.Override
    public io.cyrene.plugin.runtime.v1.DirectPayloadOrBuilder getPayloadOrBuilder() {
      if ((eventCase_ == 1) && (payloadBuilder_ != null)) {
        return payloadBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 1) {
          return (io.cyrene.plugin.runtime.v1.DirectPayload) event_;
        }
        return io.cyrene.plugin.runtime.v1.DirectPayload.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectPayload payload = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.plugin.runtime.v1.DirectPayload, io.cyrene.plugin.runtime.v1.DirectPayload.Builder, io.cyrene.plugin.runtime.v1.DirectPayloadOrBuilder> 
        getPayloadFieldBuilder() {
      if (payloadBuilder_ == null) {
        if (!(eventCase_ == 1)) {
          event_ = io.cyrene.plugin.runtime.v1.DirectPayload.getDefaultInstance();
        }
        payloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.cyrene.plugin.runtime.v1.DirectPayload, io.cyrene.plugin.runtime.v1.DirectPayload.Builder, io.cyrene.plugin.runtime.v1.DirectPayloadOrBuilder>(
                (io.cyrene.plugin.runtime.v1.DirectPayload) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 1;
      onChanged();
      return payloadBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.plugin.runtime.v1.DirectInvocationError, io.cyrene.plugin.runtime.v1.DirectInvocationError.Builder, io.cyrene.plugin.runtime.v1.DirectInvocationErrorOrBuilder> errorBuilder_;
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError error = 2;</code>
     * @return Whether the error field is set.
     */
    @java.lang.Override
    public boolean hasError() {
      return eventCase_ == 2;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError error = 2;</code>
     * @return The error.
     */
    @java.lang.Override
    public io.cyrene.plugin.runtime.v1.DirectInvocationError getError() {
      if (errorBuilder_ == null) {
        if (eventCase_ == 2) {
          return (io.cyrene.plugin.runtime.v1.DirectInvocationError) event_;
        }
        return io.cyrene.plugin.runtime.v1.DirectInvocationError.getDefaultInstance();
      } else {
        if (eventCase_ == 2) {
          return errorBuilder_.getMessage();
        }
        return io.cyrene.plugin.runtime.v1.DirectInvocationError.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError error = 2;</code>
     */
    public Builder setError(io.cyrene.plugin.runtime.v1.DirectInvocationError value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError error = 2;</code>
     */
    public Builder setError(
        io.cyrene.plugin.runtime.v1.DirectInvocationError.Builder builderForValue) {
      if (errorBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError error = 2;</code>
     */
    public Builder mergeError(io.cyrene.plugin.runtime.v1.DirectInvocationError value) {
      if (errorBuilder_ == null) {
        if (eventCase_ == 2 &&
            event_ != io.cyrene.plugin.runtime.v1.DirectInvocationError.getDefaultInstance()) {
          event_ = io.cyrene.plugin.runtime.v1.DirectInvocationError.newBuilder((io.cyrene.plugin.runtime.v1.DirectInvocationError) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 2) {
          errorBuilder_.mergeFrom(value);
        } else {
          errorBuilder_.setMessage(value);
        }
      }
      eventCase_ = 2;
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError error = 2;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 2) {
          eventCase_ = 0;
          event_ = null;
        }
        errorBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError error = 2;</code>
     */
    public io.cyrene.plugin.runtime.v1.DirectInvocationError.Builder getErrorBuilder() {
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError error = 2;</code>
     */
    @java.lang.Override
    public io.cyrene.plugin.runtime.v1.DirectInvocationErrorOrBuilder getErrorOrBuilder() {
      if ((eventCase_ == 2) && (errorBuilder_ != null)) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 2) {
          return (io.cyrene.plugin.runtime.v1.DirectInvocationError) event_;
        }
        return io.cyrene.plugin.runtime.v1.DirectInvocationError.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError error = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.plugin.runtime.v1.DirectInvocationError, io.cyrene.plugin.runtime.v1.DirectInvocationError.Builder, io.cyrene.plugin.runtime.v1.DirectInvocationErrorOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        if (!(eventCase_ == 2)) {
          event_ = io.cyrene.plugin.runtime.v1.DirectInvocationError.getDefaultInstance();
        }
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.cyrene.plugin.runtime.v1.DirectInvocationError, io.cyrene.plugin.runtime.v1.DirectInvocationError.Builder, io.cyrene.plugin.runtime.v1.DirectInvocationErrorOrBuilder>(
                (io.cyrene.plugin.runtime.v1.DirectInvocationError) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 2;
      onChanged();
      return errorBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.plugin.runtime.v1.DirectStreamEnd, io.cyrene.plugin.runtime.v1.DirectStreamEnd.Builder, io.cyrene.plugin.runtime.v1.DirectStreamEndOrBuilder> endBuilder_;
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectStreamEnd end = 3;</code>
     * @return Whether the end field is set.
     */
    @java.lang.Override
    public boolean hasEnd() {
      return eventCase_ == 3;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectStreamEnd end = 3;</code>
     * @return The end.
     */
    @java.lang.Override
    public io.cyrene.plugin.runtime.v1.DirectStreamEnd getEnd() {
      if (endBuilder_ == null) {
        if (eventCase_ == 3) {
          return (io.cyrene.plugin.runtime.v1.DirectStreamEnd) event_;
        }
        return io.cyrene.plugin.runtime.v1.DirectStreamEnd.getDefaultInstance();
      } else {
        if (eventCase_ == 3) {
          return endBuilder_.getMessage();
        }
        return io.cyrene.plugin.runtime.v1.DirectStreamEnd.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectStreamEnd end = 3;</code>
     */
    public Builder setEnd(io.cyrene.plugin.runtime.v1.DirectStreamEnd value) {
      if (endBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        event_ = value;
        onChanged();
      } else {
        endBuilder_.setMessage(value);
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectStreamEnd end = 3;</code>
     */
    public Builder setEnd(
        io.cyrene.plugin.runtime.v1.DirectStreamEnd.Builder builderForValue) {
      if (endBuilder_ == null) {
        event_ = builderForValue.build();
        onChanged();
      } else {
        endBuilder_.setMessage(builderForValue.build());
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectStreamEnd end = 3;</code>
     */
    public Builder mergeEnd(io.cyrene.plugin.runtime.v1.DirectStreamEnd value) {
      if (endBuilder_ == null) {
        if (eventCase_ == 3 &&
            event_ != io.cyrene.plugin.runtime.v1.DirectStreamEnd.getDefaultInstance()) {
          event_ = io.cyrene.plugin.runtime.v1.DirectStreamEnd.newBuilder((io.cyrene.plugin.runtime.v1.DirectStreamEnd) event_)
              .mergeFrom(value).buildPartial();
        } else {
          event_ = value;
        }
        onChanged();
      } else {
        if (eventCase_ == 3) {
          endBuilder_.mergeFrom(value);
        } else {
          endBuilder_.setMessage(value);
        }
      }
      eventCase_ = 3;
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectStreamEnd end = 3;</code>
     */
    public Builder clearEnd() {
      if (endBuilder_ == null) {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
          onChanged();
        }
      } else {
        if (eventCase_ == 3) {
          eventCase_ = 0;
          event_ = null;
        }
        endBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectStreamEnd end = 3;</code>
     */
    public io.cyrene.plugin.runtime.v1.DirectStreamEnd.Builder getEndBuilder() {
      return getEndFieldBuilder().getBuilder();
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectStreamEnd end = 3;</code>
     */
    @java.lang.Override
    public io.cyrene.plugin.runtime.v1.DirectStreamEndOrBuilder getEndOrBuilder() {
      if ((eventCase_ == 3) && (endBuilder_ != null)) {
        return endBuilder_.getMessageOrBuilder();
      } else {
        if (eventCase_ == 3) {
          return (io.cyrene.plugin.runtime.v1.DirectStreamEnd) event_;
        }
        return io.cyrene.plugin.runtime.v1.DirectStreamEnd.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectStreamEnd end = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.plugin.runtime.v1.DirectStreamEnd, io.cyrene.plugin.runtime.v1.DirectStreamEnd.Builder, io.cyrene.plugin.runtime.v1.DirectStreamEndOrBuilder> 
        getEndFieldBuilder() {
      if (endBuilder_ == null) {
        if (!(eventCase_ == 3)) {
          event_ = io.cyrene.plugin.runtime.v1.DirectStreamEnd.getDefaultInstance();
        }
        endBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.cyrene.plugin.runtime.v1.DirectStreamEnd, io.cyrene.plugin.runtime.v1.DirectStreamEnd.Builder, io.cyrene.plugin.runtime.v1.DirectStreamEndOrBuilder>(
                (io.cyrene.plugin.runtime.v1.DirectStreamEnd) event_,
                getParentForChildren(),
                isClean());
        event_ = null;
      }
      eventCase_ = 3;
      onChanged();
      return endBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cyrene.plugin.runtime.v1.DirectStreamItem)
  }

  // @@protoc_insertion_point(class_scope:cyrene.plugin.runtime.v1.DirectStreamItem)
  private static final io.cyrene.plugin.runtime.v1.DirectStreamItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.cyrene.plugin.runtime.v1.DirectStreamItem();
  }

  public static io.cyrene.plugin.runtime.v1.DirectStreamItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DirectStreamItem>
      PARSER = new com.google.protobuf.AbstractParser<DirectStreamItem>() {
    @java.lang.Override
    public DirectStreamItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DirectStreamItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DirectStreamItem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.cyrene.plugin.runtime.v1.DirectStreamItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

