// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/plugin/runtime/v1/direct_plugin_runtime.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.plugin.runtime.v1;

/**
 * Protobuf type {@code cyrene.plugin.runtime.v1.DirectInvocationError}
 */
public final class DirectInvocationError extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cyrene.plugin.runtime.v1.DirectInvocationError)
    DirectInvocationErrorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DirectInvocationError.newBuilder() to construct.
  private DirectInvocationError(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DirectInvocationError() {
    code_ = 0;
    message_ = "";
    domainCode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DirectInvocationError();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.cyrene.plugin.runtime.v1.DirectPluginRuntimeOuterClass.internal_static_cyrene_plugin_runtime_v1_DirectInvocationError_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.cyrene.plugin.runtime.v1.DirectPluginRuntimeOuterClass.internal_static_cyrene_plugin_runtime_v1_DirectInvocationError_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.cyrene.plugin.runtime.v1.DirectInvocationError.class, io.cyrene.plugin.runtime.v1.DirectInvocationError.Builder.class);
  }

  /**
   * Protobuf enum {@code cyrene.plugin.runtime.v1.DirectInvocationError.Code}
   */
  public enum Code
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CODE_UNSPECIFIED = 0;</code>
     */
    CODE_UNSPECIFIED(0),
    /**
     * <code>CODE_INVALID_REQUEST = 1;</code>
     */
    CODE_INVALID_REQUEST(1),
    /**
     * <code>CODE_METHOD_NOT_FOUND = 2;</code>
     */
    CODE_METHOD_NOT_FOUND(2),
    /**
     * <code>CODE_CANCELLED = 3;</code>
     */
    CODE_CANCELLED(3),
    /**
     * <code>CODE_DEADLINE_EXCEEDED = 4;</code>
     */
    CODE_DEADLINE_EXCEEDED(4),
    /**
     * <code>CODE_EXECUTION_FAILED = 5;</code>
     */
    CODE_EXECUTION_FAILED(5),
    /**
     * <code>CODE_UNAVAILABLE = 6;</code>
     */
    CODE_UNAVAILABLE(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CODE_UNSPECIFIED = 0;</code>
     */
    public static final int CODE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>CODE_INVALID_REQUEST = 1;</code>
     */
    public static final int CODE_INVALID_REQUEST_VALUE = 1;
    /**
     * <code>CODE_METHOD_NOT_FOUND = 2;</code>
     */
    public static final int CODE_METHOD_NOT_FOUND_VALUE = 2;
    /**
     * <code>CODE_CANCELLED = 3;</code>
     */
    public static final int CODE_CANCELLED_VALUE = 3;
    /**
     * <code>CODE_DEADLINE_EXCEEDED = 4;</code>
     */
    public static final int CODE_DEADLINE_EXCEEDED_VALUE = 4;
    /**
     * <code>CODE_EXECUTION_FAILED = 5;</code>
     */
    public static final int CODE_EXECUTION_FAILED_VALUE = 5;
    /**
     * <code>CODE_UNAVAILABLE = 6;</code>
     */
    public static final int CODE_UNAVAILABLE_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Code valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Code forNumber(int value) {
      switch (value) {
        case 0: return CODE_UNSPECIFIED;
        case 1: return CODE_INVALID_REQUEST;
        case 2: return CODE_METHOD_NOT_FOUND;
        case 3: return CODE_CANCELLED;
        case 4: return CODE_DEADLINE_EXCEEDED;
        case 5: return CODE_EXECUTION_FAILED;
        case 6: return CODE_UNAVAILABLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Code>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Code> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Code>() {
            public Code findValueByNumber(int number) {
              return Code.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.cyrene.plugin.runtime.v1.DirectInvocationError.getDescriptor().getEnumTypes().get(0);
    }

    private static final Code[] VALUES = values();

    public static Code valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Code(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:cyrene.plugin.runtime.v1.DirectInvocationError.Code)
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_ = 0;
  /**
   * <code>.cyrene.plugin.runtime.v1.DirectInvocationError.Code code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  @java.lang.Override public int getCodeValue() {
    return code_;
  }
  /**
   * <code>.cyrene.plugin.runtime.v1.DirectInvocationError.Code code = 1;</code>
   * @return The code.
   */
  @java.lang.Override public io.cyrene.plugin.runtime.v1.DirectInvocationError.Code getCode() {
    io.cyrene.plugin.runtime.v1.DirectInvocationError.Code result = io.cyrene.plugin.runtime.v1.DirectInvocationError.Code.forNumber(code_);
    return result == null ? io.cyrene.plugin.runtime.v1.DirectInvocationError.Code.UNRECOGNIZED : result;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETRYABLE_FIELD_NUMBER = 3;
  private boolean retryable_ = false;
  /**
   * <code>bool retryable = 3;</code>
   * @return The retryable.
   */
  @java.lang.Override
  public boolean getRetryable() {
    return retryable_;
  }

  public static final int DOMAIN_CODE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object domainCode_ = "";
  /**
   * <code>string domain_code = 4;</code>
   * @return The domainCode.
   */
  @java.lang.Override
  public java.lang.String getDomainCode() {
    java.lang.Object ref = domainCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      domainCode_ = s;
      return s;
    }
  }
  /**
   * <code>string domain_code = 4;</code>
   * @return The bytes for domainCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDomainCodeBytes() {
    java.lang.Object ref = domainCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      domainCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != io.cyrene.plugin.runtime.v1.DirectInvocationError.Code.CODE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (retryable_ != false) {
      output.writeBool(3, retryable_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(domainCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, domainCode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != io.cyrene.plugin.runtime.v1.DirectInvocationError.Code.CODE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, code_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (retryable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, retryable_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(domainCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, domainCode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.cyrene.plugin.runtime.v1.DirectInvocationError)) {
      return super.equals(obj);
    }
    io.cyrene.plugin.runtime.v1.DirectInvocationError other = (io.cyrene.plugin.runtime.v1.DirectInvocationError) obj;

    if (code_ != other.code_) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (getRetryable()
        != other.getRetryable()) return false;
    if (!getDomainCode()
        .equals(other.getDomainCode())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + code_;
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + RETRYABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRetryable());
    hash = (37 * hash) + DOMAIN_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getDomainCode().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.cyrene.plugin.runtime.v1.DirectInvocationError parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.plugin.runtime.v1.DirectInvocationError parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.plugin.runtime.v1.DirectInvocationError parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.plugin.runtime.v1.DirectInvocationError parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.plugin.runtime.v1.DirectInvocationError parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.plugin.runtime.v1.DirectInvocationError parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.plugin.runtime.v1.DirectInvocationError parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.plugin.runtime.v1.DirectInvocationError parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.cyrene.plugin.runtime.v1.DirectInvocationError parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.cyrene.plugin.runtime.v1.DirectInvocationError parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.cyrene.plugin.runtime.v1.DirectInvocationError parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.plugin.runtime.v1.DirectInvocationError parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.cyrene.plugin.runtime.v1.DirectInvocationError prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cyrene.plugin.runtime.v1.DirectInvocationError}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cyrene.plugin.runtime.v1.DirectInvocationError)
      io.cyrene.plugin.runtime.v1.DirectInvocationErrorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.cyrene.plugin.runtime.v1.DirectPluginRuntimeOuterClass.internal_static_cyrene_plugin_runtime_v1_DirectInvocationError_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.cyrene.plugin.runtime.v1.DirectPluginRuntimeOuterClass.internal_static_cyrene_plugin_runtime_v1_DirectInvocationError_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.cyrene.plugin.runtime.v1.DirectInvocationError.class, io.cyrene.plugin.runtime.v1.DirectInvocationError.Builder.class);
    }

    // Construct using io.cyrene.plugin.runtime.v1.DirectInvocationError.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      code_ = 0;
      message_ = "";
      retryable_ = false;
      domainCode_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.cyrene.plugin.runtime.v1.DirectPluginRuntimeOuterClass.internal_static_cyrene_plugin_runtime_v1_DirectInvocationError_descriptor;
    }

    @java.lang.Override
    public io.cyrene.plugin.runtime.v1.DirectInvocationError getDefaultInstanceForType() {
      return io.cyrene.plugin.runtime.v1.DirectInvocationError.getDefaultInstance();
    }

    @java.lang.Override
    public io.cyrene.plugin.runtime.v1.DirectInvocationError build() {
      io.cyrene.plugin.runtime.v1.DirectInvocationError result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.cyrene.plugin.runtime.v1.DirectInvocationError buildPartial() {
      io.cyrene.plugin.runtime.v1.DirectInvocationError result = new io.cyrene.plugin.runtime.v1.DirectInvocationError(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.cyrene.plugin.runtime.v1.DirectInvocationError result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.code_ = code_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.retryable_ = retryable_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.domainCode_ = domainCode_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.cyrene.plugin.runtime.v1.DirectInvocationError) {
        return mergeFrom((io.cyrene.plugin.runtime.v1.DirectInvocationError)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.cyrene.plugin.runtime.v1.DirectInvocationError other) {
      if (other == io.cyrene.plugin.runtime.v1.DirectInvocationError.getDefaultInstance()) return this;
      if (other.code_ != 0) {
        setCodeValue(other.getCodeValue());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getRetryable() != false) {
        setRetryable(other.getRetryable());
      }
      if (!other.getDomainCode().isEmpty()) {
        domainCode_ = other.domainCode_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              code_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              retryable_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              domainCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int code_ = 0;
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError.Code code = 1;</code>
     * @return The enum numeric value on the wire for code.
     */
    @java.lang.Override public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError.Code code = 1;</code>
     * @param value The enum numeric value on the wire for code to set.
     * @return This builder for chaining.
     */
    public Builder setCodeValue(int value) {
      code_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError.Code code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public io.cyrene.plugin.runtime.v1.DirectInvocationError.Code getCode() {
      io.cyrene.plugin.runtime.v1.DirectInvocationError.Code result = io.cyrene.plugin.runtime.v1.DirectInvocationError.Code.forNumber(code_);
      return result == null ? io.cyrene.plugin.runtime.v1.DirectInvocationError.Code.UNRECOGNIZED : result;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError.Code code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(io.cyrene.plugin.runtime.v1.DirectInvocationError.Code value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      code_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.cyrene.plugin.runtime.v1.DirectInvocationError.Code code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean retryable_ ;
    /**
     * <code>bool retryable = 3;</code>
     * @return The retryable.
     */
    @java.lang.Override
    public boolean getRetryable() {
      return retryable_;
    }
    /**
     * <code>bool retryable = 3;</code>
     * @param value The retryable to set.
     * @return This builder for chaining.
     */
    public Builder setRetryable(boolean value) {

      retryable_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool retryable = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRetryable() {
      bitField0_ = (bitField0_ & ~0x00000004);
      retryable_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object domainCode_ = "";
    /**
     * <code>string domain_code = 4;</code>
     * @return The domainCode.
     */
    public java.lang.String getDomainCode() {
      java.lang.Object ref = domainCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domainCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string domain_code = 4;</code>
     * @return The bytes for domainCode.
     */
    public com.google.protobuf.ByteString
        getDomainCodeBytes() {
      java.lang.Object ref = domainCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domainCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string domain_code = 4;</code>
     * @param value The domainCode to set.
     * @return This builder for chaining.
     */
    public Builder setDomainCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      domainCode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string domain_code = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDomainCode() {
      domainCode_ = getDefaultInstance().getDomainCode();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string domain_code = 4;</code>
     * @param value The bytes for domainCode to set.
     * @return This builder for chaining.
     */
    public Builder setDomainCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      domainCode_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cyrene.plugin.runtime.v1.DirectInvocationError)
  }

  // @@protoc_insertion_point(class_scope:cyrene.plugin.runtime.v1.DirectInvocationError)
  private static final io.cyrene.plugin.runtime.v1.DirectInvocationError DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.cyrene.plugin.runtime.v1.DirectInvocationError();
  }

  public static io.cyrene.plugin.runtime.v1.DirectInvocationError getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DirectInvocationError>
      PARSER = new com.google.protobuf.AbstractParser<DirectInvocationError>() {
    @java.lang.Override
    public DirectInvocationError parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DirectInvocationError> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DirectInvocationError> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.cyrene.plugin.runtime.v1.DirectInvocationError getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

