// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/plugin/runtime/v1/direct_plugin_runtime.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.plugin.runtime.v1;

public interface DirectInvocationErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cyrene.plugin.runtime.v1.DirectInvocationError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.cyrene.plugin.runtime.v1.DirectInvocationError.Code code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.cyrene.plugin.runtime.v1.DirectInvocationError.Code code = 1;</code>
   * @return The code.
   */
  io.cyrene.plugin.runtime.v1.DirectInvocationError.Code getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>bool retryable = 3;</code>
   * @return The retryable.
   */
  boolean getRetryable();

  /**
   * <code>string domain_code = 4;</code>
   * @return The domainCode.
   */
  java.lang.String getDomainCode();
  /**
   * <code>string domain_code = 4;</code>
   * @return The bytes for domainCode.
   */
  com.google.protobuf.ByteString
      getDomainCodeBytes();
}
