// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/message/connector/v1/message_connector.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.message.connector.v1;

/**
 * Protobuf type {@code cyrene.message.connector.v1.ConversationScope}
 */
public final class ConversationScope extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cyrene.message.connector.v1.ConversationScope)
    ConversationScopeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConversationScope.newBuilder() to construct.
  private ConversationScope(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConversationScope() {
    vendor_ = "";
    accountId_ = "";
    conversationId_ = "";
    kind_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConversationScope();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.cyrene.proto.message.connector.v1.MessageConnectorProto.internal_static_cyrene_message_connector_v1_ConversationScope_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.cyrene.proto.message.connector.v1.MessageConnectorProto.internal_static_cyrene_message_connector_v1_ConversationScope_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.cyrene.proto.message.connector.v1.ConversationScope.class, io.cyrene.proto.message.connector.v1.ConversationScope.Builder.class);
  }

  public static final int VENDOR_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object vendor_ = "";
  /**
   * <pre>
   * Canonical vendor/protocol identifier, for example "onebot.v11".
   * </pre>
   *
   * <code>string vendor = 1;</code>
   * @return The vendor.
   */
  @java.lang.Override
  public java.lang.String getVendor() {
    java.lang.Object ref = vendor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vendor_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Canonical vendor/protocol identifier, for example "onebot.v11".
   * </pre>
   *
   * <code>string vendor = 1;</code>
   * @return The bytes for vendor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVendorBytes() {
    java.lang.Object ref = vendor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vendor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNT_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object accountId_ = "";
  /**
   * <pre>
   * Vendor account or bot identity that owns this conversation.
   * </pre>
   *
   * <code>string account_id = 2;</code>
   * @return The accountId.
   */
  @java.lang.Override
  public java.lang.String getAccountId() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Vendor account or bot identity that owns this conversation.
   * </pre>
   *
   * <code>string account_id = 2;</code>
   * @return The bytes for accountId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccountIdBytes() {
    java.lang.Object ref = accountId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONVERSATION_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object conversationId_ = "";
  /**
   * <pre>
   * Vendor-resolvable user, group, or channel identity.
   * </pre>
   *
   * <code>string conversation_id = 3;</code>
   * @return The conversationId.
   */
  @java.lang.Override
  public java.lang.String getConversationId() {
    java.lang.Object ref = conversationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      conversationId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Vendor-resolvable user, group, or channel identity.
   * </pre>
   *
   * <code>string conversation_id = 3;</code>
   * @return The bytes for conversationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConversationIdBytes() {
    java.lang.Object ref = conversationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      conversationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KIND_FIELD_NUMBER = 4;
  private int kind_ = 0;
  /**
   * <code>.cyrene.message.connector.v1.ConversationKind kind = 4;</code>
   * @return The enum numeric value on the wire for kind.
   */
  @java.lang.Override public int getKindValue() {
    return kind_;
  }
  /**
   * <code>.cyrene.message.connector.v1.ConversationKind kind = 4;</code>
   * @return The kind.
   */
  @java.lang.Override public io.cyrene.proto.message.connector.v1.ConversationKind getKind() {
    io.cyrene.proto.message.connector.v1.ConversationKind result = io.cyrene.proto.message.connector.v1.ConversationKind.forNumber(kind_);
    return result == null ? io.cyrene.proto.message.connector.v1.ConversationKind.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vendor_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vendor_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accountId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(conversationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, conversationId_);
    }
    if (kind_ != io.cyrene.proto.message.connector.v1.ConversationKind.CONVERSATION_KIND_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, kind_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vendor_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vendor_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accountId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accountId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(conversationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, conversationId_);
    }
    if (kind_ != io.cyrene.proto.message.connector.v1.ConversationKind.CONVERSATION_KIND_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, kind_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.cyrene.proto.message.connector.v1.ConversationScope)) {
      return super.equals(obj);
    }
    io.cyrene.proto.message.connector.v1.ConversationScope other = (io.cyrene.proto.message.connector.v1.ConversationScope) obj;

    if (!getVendor()
        .equals(other.getVendor())) return false;
    if (!getAccountId()
        .equals(other.getAccountId())) return false;
    if (!getConversationId()
        .equals(other.getConversationId())) return false;
    if (kind_ != other.kind_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VENDOR_FIELD_NUMBER;
    hash = (53 * hash) + getVendor().hashCode();
    hash = (37 * hash) + ACCOUNT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAccountId().hashCode();
    hash = (37 * hash) + CONVERSATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConversationId().hashCode();
    hash = (37 * hash) + KIND_FIELD_NUMBER;
    hash = (53 * hash) + kind_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.cyrene.proto.message.connector.v1.ConversationScope parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.message.connector.v1.ConversationScope parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.message.connector.v1.ConversationScope parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.message.connector.v1.ConversationScope parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.message.connector.v1.ConversationScope parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.message.connector.v1.ConversationScope parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.message.connector.v1.ConversationScope parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.message.connector.v1.ConversationScope parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.cyrene.proto.message.connector.v1.ConversationScope parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.cyrene.proto.message.connector.v1.ConversationScope parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.cyrene.proto.message.connector.v1.ConversationScope parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.message.connector.v1.ConversationScope parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.cyrene.proto.message.connector.v1.ConversationScope prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cyrene.message.connector.v1.ConversationScope}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cyrene.message.connector.v1.ConversationScope)
      io.cyrene.proto.message.connector.v1.ConversationScopeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.cyrene.proto.message.connector.v1.MessageConnectorProto.internal_static_cyrene_message_connector_v1_ConversationScope_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.cyrene.proto.message.connector.v1.MessageConnectorProto.internal_static_cyrene_message_connector_v1_ConversationScope_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.cyrene.proto.message.connector.v1.ConversationScope.class, io.cyrene.proto.message.connector.v1.ConversationScope.Builder.class);
    }

    // Construct using io.cyrene.proto.message.connector.v1.ConversationScope.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      vendor_ = "";
      accountId_ = "";
      conversationId_ = "";
      kind_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.cyrene.proto.message.connector.v1.MessageConnectorProto.internal_static_cyrene_message_connector_v1_ConversationScope_descriptor;
    }

    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.ConversationScope getDefaultInstanceForType() {
      return io.cyrene.proto.message.connector.v1.ConversationScope.getDefaultInstance();
    }

    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.ConversationScope build() {
      io.cyrene.proto.message.connector.v1.ConversationScope result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.ConversationScope buildPartial() {
      io.cyrene.proto.message.connector.v1.ConversationScope result = new io.cyrene.proto.message.connector.v1.ConversationScope(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.cyrene.proto.message.connector.v1.ConversationScope result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.vendor_ = vendor_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.accountId_ = accountId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.conversationId_ = conversationId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.kind_ = kind_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.cyrene.proto.message.connector.v1.ConversationScope) {
        return mergeFrom((io.cyrene.proto.message.connector.v1.ConversationScope)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.cyrene.proto.message.connector.v1.ConversationScope other) {
      if (other == io.cyrene.proto.message.connector.v1.ConversationScope.getDefaultInstance()) return this;
      if (!other.getVendor().isEmpty()) {
        vendor_ = other.vendor_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getAccountId().isEmpty()) {
        accountId_ = other.accountId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getConversationId().isEmpty()) {
        conversationId_ = other.conversationId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.kind_ != 0) {
        setKindValue(other.getKindValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              vendor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              accountId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              conversationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              kind_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object vendor_ = "";
    /**
     * <pre>
     * Canonical vendor/protocol identifier, for example "onebot.v11".
     * </pre>
     *
     * <code>string vendor = 1;</code>
     * @return The vendor.
     */
    public java.lang.String getVendor() {
      java.lang.Object ref = vendor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vendor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Canonical vendor/protocol identifier, for example "onebot.v11".
     * </pre>
     *
     * <code>string vendor = 1;</code>
     * @return The bytes for vendor.
     */
    public com.google.protobuf.ByteString
        getVendorBytes() {
      java.lang.Object ref = vendor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vendor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Canonical vendor/protocol identifier, for example "onebot.v11".
     * </pre>
     *
     * <code>string vendor = 1;</code>
     * @param value The vendor to set.
     * @return This builder for chaining.
     */
    public Builder setVendor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      vendor_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Canonical vendor/protocol identifier, for example "onebot.v11".
     * </pre>
     *
     * <code>string vendor = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVendor() {
      vendor_ = getDefaultInstance().getVendor();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Canonical vendor/protocol identifier, for example "onebot.v11".
     * </pre>
     *
     * <code>string vendor = 1;</code>
     * @param value The bytes for vendor to set.
     * @return This builder for chaining.
     */
    public Builder setVendorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      vendor_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object accountId_ = "";
    /**
     * <pre>
     * Vendor account or bot identity that owns this conversation.
     * </pre>
     *
     * <code>string account_id = 2;</code>
     * @return The accountId.
     */
    public java.lang.String getAccountId() {
      java.lang.Object ref = accountId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Vendor account or bot identity that owns this conversation.
     * </pre>
     *
     * <code>string account_id = 2;</code>
     * @return The bytes for accountId.
     */
    public com.google.protobuf.ByteString
        getAccountIdBytes() {
      java.lang.Object ref = accountId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Vendor account or bot identity that owns this conversation.
     * </pre>
     *
     * <code>string account_id = 2;</code>
     * @param value The accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      accountId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vendor account or bot identity that owns this conversation.
     * </pre>
     *
     * <code>string account_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccountId() {
      accountId_ = getDefaultInstance().getAccountId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vendor account or bot identity that owns this conversation.
     * </pre>
     *
     * <code>string account_id = 2;</code>
     * @param value The bytes for accountId to set.
     * @return This builder for chaining.
     */
    public Builder setAccountIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      accountId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object conversationId_ = "";
    /**
     * <pre>
     * Vendor-resolvable user, group, or channel identity.
     * </pre>
     *
     * <code>string conversation_id = 3;</code>
     * @return The conversationId.
     */
    public java.lang.String getConversationId() {
      java.lang.Object ref = conversationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conversationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Vendor-resolvable user, group, or channel identity.
     * </pre>
     *
     * <code>string conversation_id = 3;</code>
     * @return The bytes for conversationId.
     */
    public com.google.protobuf.ByteString
        getConversationIdBytes() {
      java.lang.Object ref = conversationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conversationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Vendor-resolvable user, group, or channel identity.
     * </pre>
     *
     * <code>string conversation_id = 3;</code>
     * @param value The conversationId to set.
     * @return This builder for chaining.
     */
    public Builder setConversationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      conversationId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vendor-resolvable user, group, or channel identity.
     * </pre>
     *
     * <code>string conversation_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversationId() {
      conversationId_ = getDefaultInstance().getConversationId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Vendor-resolvable user, group, or channel identity.
     * </pre>
     *
     * <code>string conversation_id = 3;</code>
     * @param value The bytes for conversationId to set.
     * @return This builder for chaining.
     */
    public Builder setConversationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      conversationId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int kind_ = 0;
    /**
     * <code>.cyrene.message.connector.v1.ConversationKind kind = 4;</code>
     * @return The enum numeric value on the wire for kind.
     */
    @java.lang.Override public int getKindValue() {
      return kind_;
    }
    /**
     * <code>.cyrene.message.connector.v1.ConversationKind kind = 4;</code>
     * @param value The enum numeric value on the wire for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKindValue(int value) {
      kind_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.ConversationKind kind = 4;</code>
     * @return The kind.
     */
    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.ConversationKind getKind() {
      io.cyrene.proto.message.connector.v1.ConversationKind result = io.cyrene.proto.message.connector.v1.ConversationKind.forNumber(kind_);
      return result == null ? io.cyrene.proto.message.connector.v1.ConversationKind.UNRECOGNIZED : result;
    }
    /**
     * <code>.cyrene.message.connector.v1.ConversationKind kind = 4;</code>
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(io.cyrene.proto.message.connector.v1.ConversationKind value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      kind_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.ConversationKind kind = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      bitField0_ = (bitField0_ & ~0x00000008);
      kind_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cyrene.message.connector.v1.ConversationScope)
  }

  // @@protoc_insertion_point(class_scope:cyrene.message.connector.v1.ConversationScope)
  private static final io.cyrene.proto.message.connector.v1.ConversationScope DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.cyrene.proto.message.connector.v1.ConversationScope();
  }

  public static io.cyrene.proto.message.connector.v1.ConversationScope getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConversationScope>
      PARSER = new com.google.protobuf.AbstractParser<ConversationScope>() {
    @java.lang.Override
    public ConversationScope parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConversationScope> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConversationScope> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.cyrene.proto.message.connector.v1.ConversationScope getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

