// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/message/connector/v1/message_connector.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.message.connector.v1;

/**
 * Protobuf type {@code cyrene.message.connector.v1.MessageContentPart}
 */
public final class MessageContentPart extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cyrene.message.connector.v1.MessageContentPart)
    MessageContentPartOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageContentPart.newBuilder() to construct.
  private MessageContentPart(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageContentPart() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageContentPart();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.cyrene.proto.message.connector.v1.MessageConnectorProto.internal_static_cyrene_message_connector_v1_MessageContentPart_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.cyrene.proto.message.connector.v1.MessageConnectorProto.internal_static_cyrene_message_connector_v1_MessageContentPart_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.cyrene.proto.message.connector.v1.MessageContentPart.class, io.cyrene.proto.message.connector.v1.MessageContentPart.Builder.class);
  }

  private int kindCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object kind_;
  public enum KindCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TEXT(1),
    MENTION(2),
    IMAGE(3),
    FILE(4),
    KIND_NOT_SET(0);
    private final int value;
    private KindCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static KindCase valueOf(int value) {
      return forNumber(value);
    }

    public static KindCase forNumber(int value) {
      switch (value) {
        case 1: return TEXT;
        case 2: return MENTION;
        case 3: return IMAGE;
        case 4: return FILE;
        case 0: return KIND_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public KindCase
  getKindCase() {
    return KindCase.forNumber(
        kindCase_);
  }

  public static final int TEXT_FIELD_NUMBER = 1;
  /**
   * <code>.cyrene.message.connector.v1.TextContent text = 1;</code>
   * @return Whether the text field is set.
   */
  @java.lang.Override
  public boolean hasText() {
    return kindCase_ == 1;
  }
  /**
   * <code>.cyrene.message.connector.v1.TextContent text = 1;</code>
   * @return The text.
   */
  @java.lang.Override
  public io.cyrene.proto.message.connector.v1.TextContent getText() {
    if (kindCase_ == 1) {
       return (io.cyrene.proto.message.connector.v1.TextContent) kind_;
    }
    return io.cyrene.proto.message.connector.v1.TextContent.getDefaultInstance();
  }
  /**
   * <code>.cyrene.message.connector.v1.TextContent text = 1;</code>
   */
  @java.lang.Override
  public io.cyrene.proto.message.connector.v1.TextContentOrBuilder getTextOrBuilder() {
    if (kindCase_ == 1) {
       return (io.cyrene.proto.message.connector.v1.TextContent) kind_;
    }
    return io.cyrene.proto.message.connector.v1.TextContent.getDefaultInstance();
  }

  public static final int MENTION_FIELD_NUMBER = 2;
  /**
   * <code>.cyrene.message.connector.v1.MentionContent mention = 2;</code>
   * @return Whether the mention field is set.
   */
  @java.lang.Override
  public boolean hasMention() {
    return kindCase_ == 2;
  }
  /**
   * <code>.cyrene.message.connector.v1.MentionContent mention = 2;</code>
   * @return The mention.
   */
  @java.lang.Override
  public io.cyrene.proto.message.connector.v1.MentionContent getMention() {
    if (kindCase_ == 2) {
       return (io.cyrene.proto.message.connector.v1.MentionContent) kind_;
    }
    return io.cyrene.proto.message.connector.v1.MentionContent.getDefaultInstance();
  }
  /**
   * <code>.cyrene.message.connector.v1.MentionContent mention = 2;</code>
   */
  @java.lang.Override
  public io.cyrene.proto.message.connector.v1.MentionContentOrBuilder getMentionOrBuilder() {
    if (kindCase_ == 2) {
       return (io.cyrene.proto.message.connector.v1.MentionContent) kind_;
    }
    return io.cyrene.proto.message.connector.v1.MentionContent.getDefaultInstance();
  }

  public static final int IMAGE_FIELD_NUMBER = 3;
  /**
   * <code>.cyrene.message.connector.v1.ImageContent image = 3;</code>
   * @return Whether the image field is set.
   */
  @java.lang.Override
  public boolean hasImage() {
    return kindCase_ == 3;
  }
  /**
   * <code>.cyrene.message.connector.v1.ImageContent image = 3;</code>
   * @return The image.
   */
  @java.lang.Override
  public io.cyrene.proto.message.connector.v1.ImageContent getImage() {
    if (kindCase_ == 3) {
       return (io.cyrene.proto.message.connector.v1.ImageContent) kind_;
    }
    return io.cyrene.proto.message.connector.v1.ImageContent.getDefaultInstance();
  }
  /**
   * <code>.cyrene.message.connector.v1.ImageContent image = 3;</code>
   */
  @java.lang.Override
  public io.cyrene.proto.message.connector.v1.ImageContentOrBuilder getImageOrBuilder() {
    if (kindCase_ == 3) {
       return (io.cyrene.proto.message.connector.v1.ImageContent) kind_;
    }
    return io.cyrene.proto.message.connector.v1.ImageContent.getDefaultInstance();
  }

  public static final int FILE_FIELD_NUMBER = 4;
  /**
   * <code>.cyrene.message.connector.v1.FileContent file = 4;</code>
   * @return Whether the file field is set.
   */
  @java.lang.Override
  public boolean hasFile() {
    return kindCase_ == 4;
  }
  /**
   * <code>.cyrene.message.connector.v1.FileContent file = 4;</code>
   * @return The file.
   */
  @java.lang.Override
  public io.cyrene.proto.message.connector.v1.FileContent getFile() {
    if (kindCase_ == 4) {
       return (io.cyrene.proto.message.connector.v1.FileContent) kind_;
    }
    return io.cyrene.proto.message.connector.v1.FileContent.getDefaultInstance();
  }
  /**
   * <code>.cyrene.message.connector.v1.FileContent file = 4;</code>
   */
  @java.lang.Override
  public io.cyrene.proto.message.connector.v1.FileContentOrBuilder getFileOrBuilder() {
    if (kindCase_ == 4) {
       return (io.cyrene.proto.message.connector.v1.FileContent) kind_;
    }
    return io.cyrene.proto.message.connector.v1.FileContent.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kindCase_ == 1) {
      output.writeMessage(1, (io.cyrene.proto.message.connector.v1.TextContent) kind_);
    }
    if (kindCase_ == 2) {
      output.writeMessage(2, (io.cyrene.proto.message.connector.v1.MentionContent) kind_);
    }
    if (kindCase_ == 3) {
      output.writeMessage(3, (io.cyrene.proto.message.connector.v1.ImageContent) kind_);
    }
    if (kindCase_ == 4) {
      output.writeMessage(4, (io.cyrene.proto.message.connector.v1.FileContent) kind_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kindCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (io.cyrene.proto.message.connector.v1.TextContent) kind_);
    }
    if (kindCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (io.cyrene.proto.message.connector.v1.MentionContent) kind_);
    }
    if (kindCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (io.cyrene.proto.message.connector.v1.ImageContent) kind_);
    }
    if (kindCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (io.cyrene.proto.message.connector.v1.FileContent) kind_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.cyrene.proto.message.connector.v1.MessageContentPart)) {
      return super.equals(obj);
    }
    io.cyrene.proto.message.connector.v1.MessageContentPart other = (io.cyrene.proto.message.connector.v1.MessageContentPart) obj;

    if (!getKindCase().equals(other.getKindCase())) return false;
    switch (kindCase_) {
      case 1:
        if (!getText()
            .equals(other.getText())) return false;
        break;
      case 2:
        if (!getMention()
            .equals(other.getMention())) return false;
        break;
      case 3:
        if (!getImage()
            .equals(other.getImage())) return false;
        break;
      case 4:
        if (!getFile()
            .equals(other.getFile())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (kindCase_) {
      case 1:
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
        break;
      case 2:
        hash = (37 * hash) + MENTION_FIELD_NUMBER;
        hash = (53 * hash) + getMention().hashCode();
        break;
      case 3:
        hash = (37 * hash) + IMAGE_FIELD_NUMBER;
        hash = (53 * hash) + getImage().hashCode();
        break;
      case 4:
        hash = (37 * hash) + FILE_FIELD_NUMBER;
        hash = (53 * hash) + getFile().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.cyrene.proto.message.connector.v1.MessageContentPart parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.message.connector.v1.MessageContentPart parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.message.connector.v1.MessageContentPart parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.message.connector.v1.MessageContentPart parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.message.connector.v1.MessageContentPart parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.message.connector.v1.MessageContentPart parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.message.connector.v1.MessageContentPart parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.message.connector.v1.MessageContentPart parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.cyrene.proto.message.connector.v1.MessageContentPart parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.cyrene.proto.message.connector.v1.MessageContentPart parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.cyrene.proto.message.connector.v1.MessageContentPart parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.message.connector.v1.MessageContentPart parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.cyrene.proto.message.connector.v1.MessageContentPart prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cyrene.message.connector.v1.MessageContentPart}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cyrene.message.connector.v1.MessageContentPart)
      io.cyrene.proto.message.connector.v1.MessageContentPartOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.cyrene.proto.message.connector.v1.MessageConnectorProto.internal_static_cyrene_message_connector_v1_MessageContentPart_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.cyrene.proto.message.connector.v1.MessageConnectorProto.internal_static_cyrene_message_connector_v1_MessageContentPart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.cyrene.proto.message.connector.v1.MessageContentPart.class, io.cyrene.proto.message.connector.v1.MessageContentPart.Builder.class);
    }

    // Construct using io.cyrene.proto.message.connector.v1.MessageContentPart.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (textBuilder_ != null) {
        textBuilder_.clear();
      }
      if (mentionBuilder_ != null) {
        mentionBuilder_.clear();
      }
      if (imageBuilder_ != null) {
        imageBuilder_.clear();
      }
      if (fileBuilder_ != null) {
        fileBuilder_.clear();
      }
      kindCase_ = 0;
      kind_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.cyrene.proto.message.connector.v1.MessageConnectorProto.internal_static_cyrene_message_connector_v1_MessageContentPart_descriptor;
    }

    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.MessageContentPart getDefaultInstanceForType() {
      return io.cyrene.proto.message.connector.v1.MessageContentPart.getDefaultInstance();
    }

    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.MessageContentPart build() {
      io.cyrene.proto.message.connector.v1.MessageContentPart result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.MessageContentPart buildPartial() {
      io.cyrene.proto.message.connector.v1.MessageContentPart result = new io.cyrene.proto.message.connector.v1.MessageContentPart(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(io.cyrene.proto.message.connector.v1.MessageContentPart result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(io.cyrene.proto.message.connector.v1.MessageContentPart result) {
      result.kindCase_ = kindCase_;
      result.kind_ = this.kind_;
      if (kindCase_ == 1 &&
          textBuilder_ != null) {
        result.kind_ = textBuilder_.build();
      }
      if (kindCase_ == 2 &&
          mentionBuilder_ != null) {
        result.kind_ = mentionBuilder_.build();
      }
      if (kindCase_ == 3 &&
          imageBuilder_ != null) {
        result.kind_ = imageBuilder_.build();
      }
      if (kindCase_ == 4 &&
          fileBuilder_ != null) {
        result.kind_ = fileBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.cyrene.proto.message.connector.v1.MessageContentPart) {
        return mergeFrom((io.cyrene.proto.message.connector.v1.MessageContentPart)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.cyrene.proto.message.connector.v1.MessageContentPart other) {
      if (other == io.cyrene.proto.message.connector.v1.MessageContentPart.getDefaultInstance()) return this;
      switch (other.getKindCase()) {
        case TEXT: {
          mergeText(other.getText());
          break;
        }
        case MENTION: {
          mergeMention(other.getMention());
          break;
        }
        case IMAGE: {
          mergeImage(other.getImage());
          break;
        }
        case FILE: {
          mergeFile(other.getFile());
          break;
        }
        case KIND_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTextFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMentionFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getImageFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getFileFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int kindCase_ = 0;
    private java.lang.Object kind_;
    public KindCase
        getKindCase() {
      return KindCase.forNumber(
          kindCase_);
    }

    public Builder clearKind() {
      kindCase_ = 0;
      kind_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.proto.message.connector.v1.TextContent, io.cyrene.proto.message.connector.v1.TextContent.Builder, io.cyrene.proto.message.connector.v1.TextContentOrBuilder> textBuilder_;
    /**
     * <code>.cyrene.message.connector.v1.TextContent text = 1;</code>
     * @return Whether the text field is set.
     */
    @java.lang.Override
    public boolean hasText() {
      return kindCase_ == 1;
    }
    /**
     * <code>.cyrene.message.connector.v1.TextContent text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.TextContent getText() {
      if (textBuilder_ == null) {
        if (kindCase_ == 1) {
          return (io.cyrene.proto.message.connector.v1.TextContent) kind_;
        }
        return io.cyrene.proto.message.connector.v1.TextContent.getDefaultInstance();
      } else {
        if (kindCase_ == 1) {
          return textBuilder_.getMessage();
        }
        return io.cyrene.proto.message.connector.v1.TextContent.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.message.connector.v1.TextContent text = 1;</code>
     */
    public Builder setText(io.cyrene.proto.message.connector.v1.TextContent value) {
      if (textBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        textBuilder_.setMessage(value);
      }
      kindCase_ = 1;
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.TextContent text = 1;</code>
     */
    public Builder setText(
        io.cyrene.proto.message.connector.v1.TextContent.Builder builderForValue) {
      if (textBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        textBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 1;
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.TextContent text = 1;</code>
     */
    public Builder mergeText(io.cyrene.proto.message.connector.v1.TextContent value) {
      if (textBuilder_ == null) {
        if (kindCase_ == 1 &&
            kind_ != io.cyrene.proto.message.connector.v1.TextContent.getDefaultInstance()) {
          kind_ = io.cyrene.proto.message.connector.v1.TextContent.newBuilder((io.cyrene.proto.message.connector.v1.TextContent) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 1) {
          textBuilder_.mergeFrom(value);
        } else {
          textBuilder_.setMessage(value);
        }
      }
      kindCase_ = 1;
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.TextContent text = 1;</code>
     */
    public Builder clearText() {
      if (textBuilder_ == null) {
        if (kindCase_ == 1) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 1) {
          kindCase_ = 0;
          kind_ = null;
        }
        textBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.TextContent text = 1;</code>
     */
    public io.cyrene.proto.message.connector.v1.TextContent.Builder getTextBuilder() {
      return getTextFieldBuilder().getBuilder();
    }
    /**
     * <code>.cyrene.message.connector.v1.TextContent text = 1;</code>
     */
    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.TextContentOrBuilder getTextOrBuilder() {
      if ((kindCase_ == 1) && (textBuilder_ != null)) {
        return textBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 1) {
          return (io.cyrene.proto.message.connector.v1.TextContent) kind_;
        }
        return io.cyrene.proto.message.connector.v1.TextContent.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.message.connector.v1.TextContent text = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.proto.message.connector.v1.TextContent, io.cyrene.proto.message.connector.v1.TextContent.Builder, io.cyrene.proto.message.connector.v1.TextContentOrBuilder> 
        getTextFieldBuilder() {
      if (textBuilder_ == null) {
        if (!(kindCase_ == 1)) {
          kind_ = io.cyrene.proto.message.connector.v1.TextContent.getDefaultInstance();
        }
        textBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.cyrene.proto.message.connector.v1.TextContent, io.cyrene.proto.message.connector.v1.TextContent.Builder, io.cyrene.proto.message.connector.v1.TextContentOrBuilder>(
                (io.cyrene.proto.message.connector.v1.TextContent) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 1;
      onChanged();
      return textBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.proto.message.connector.v1.MentionContent, io.cyrene.proto.message.connector.v1.MentionContent.Builder, io.cyrene.proto.message.connector.v1.MentionContentOrBuilder> mentionBuilder_;
    /**
     * <code>.cyrene.message.connector.v1.MentionContent mention = 2;</code>
     * @return Whether the mention field is set.
     */
    @java.lang.Override
    public boolean hasMention() {
      return kindCase_ == 2;
    }
    /**
     * <code>.cyrene.message.connector.v1.MentionContent mention = 2;</code>
     * @return The mention.
     */
    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.MentionContent getMention() {
      if (mentionBuilder_ == null) {
        if (kindCase_ == 2) {
          return (io.cyrene.proto.message.connector.v1.MentionContent) kind_;
        }
        return io.cyrene.proto.message.connector.v1.MentionContent.getDefaultInstance();
      } else {
        if (kindCase_ == 2) {
          return mentionBuilder_.getMessage();
        }
        return io.cyrene.proto.message.connector.v1.MentionContent.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.message.connector.v1.MentionContent mention = 2;</code>
     */
    public Builder setMention(io.cyrene.proto.message.connector.v1.MentionContent value) {
      if (mentionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        mentionBuilder_.setMessage(value);
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.MentionContent mention = 2;</code>
     */
    public Builder setMention(
        io.cyrene.proto.message.connector.v1.MentionContent.Builder builderForValue) {
      if (mentionBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        mentionBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.MentionContent mention = 2;</code>
     */
    public Builder mergeMention(io.cyrene.proto.message.connector.v1.MentionContent value) {
      if (mentionBuilder_ == null) {
        if (kindCase_ == 2 &&
            kind_ != io.cyrene.proto.message.connector.v1.MentionContent.getDefaultInstance()) {
          kind_ = io.cyrene.proto.message.connector.v1.MentionContent.newBuilder((io.cyrene.proto.message.connector.v1.MentionContent) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 2) {
          mentionBuilder_.mergeFrom(value);
        } else {
          mentionBuilder_.setMessage(value);
        }
      }
      kindCase_ = 2;
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.MentionContent mention = 2;</code>
     */
    public Builder clearMention() {
      if (mentionBuilder_ == null) {
        if (kindCase_ == 2) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 2) {
          kindCase_ = 0;
          kind_ = null;
        }
        mentionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.MentionContent mention = 2;</code>
     */
    public io.cyrene.proto.message.connector.v1.MentionContent.Builder getMentionBuilder() {
      return getMentionFieldBuilder().getBuilder();
    }
    /**
     * <code>.cyrene.message.connector.v1.MentionContent mention = 2;</code>
     */
    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.MentionContentOrBuilder getMentionOrBuilder() {
      if ((kindCase_ == 2) && (mentionBuilder_ != null)) {
        return mentionBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 2) {
          return (io.cyrene.proto.message.connector.v1.MentionContent) kind_;
        }
        return io.cyrene.proto.message.connector.v1.MentionContent.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.message.connector.v1.MentionContent mention = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.proto.message.connector.v1.MentionContent, io.cyrene.proto.message.connector.v1.MentionContent.Builder, io.cyrene.proto.message.connector.v1.MentionContentOrBuilder> 
        getMentionFieldBuilder() {
      if (mentionBuilder_ == null) {
        if (!(kindCase_ == 2)) {
          kind_ = io.cyrene.proto.message.connector.v1.MentionContent.getDefaultInstance();
        }
        mentionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.cyrene.proto.message.connector.v1.MentionContent, io.cyrene.proto.message.connector.v1.MentionContent.Builder, io.cyrene.proto.message.connector.v1.MentionContentOrBuilder>(
                (io.cyrene.proto.message.connector.v1.MentionContent) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 2;
      onChanged();
      return mentionBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.proto.message.connector.v1.ImageContent, io.cyrene.proto.message.connector.v1.ImageContent.Builder, io.cyrene.proto.message.connector.v1.ImageContentOrBuilder> imageBuilder_;
    /**
     * <code>.cyrene.message.connector.v1.ImageContent image = 3;</code>
     * @return Whether the image field is set.
     */
    @java.lang.Override
    public boolean hasImage() {
      return kindCase_ == 3;
    }
    /**
     * <code>.cyrene.message.connector.v1.ImageContent image = 3;</code>
     * @return The image.
     */
    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.ImageContent getImage() {
      if (imageBuilder_ == null) {
        if (kindCase_ == 3) {
          return (io.cyrene.proto.message.connector.v1.ImageContent) kind_;
        }
        return io.cyrene.proto.message.connector.v1.ImageContent.getDefaultInstance();
      } else {
        if (kindCase_ == 3) {
          return imageBuilder_.getMessage();
        }
        return io.cyrene.proto.message.connector.v1.ImageContent.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.message.connector.v1.ImageContent image = 3;</code>
     */
    public Builder setImage(io.cyrene.proto.message.connector.v1.ImageContent value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        imageBuilder_.setMessage(value);
      }
      kindCase_ = 3;
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.ImageContent image = 3;</code>
     */
    public Builder setImage(
        io.cyrene.proto.message.connector.v1.ImageContent.Builder builderForValue) {
      if (imageBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        imageBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 3;
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.ImageContent image = 3;</code>
     */
    public Builder mergeImage(io.cyrene.proto.message.connector.v1.ImageContent value) {
      if (imageBuilder_ == null) {
        if (kindCase_ == 3 &&
            kind_ != io.cyrene.proto.message.connector.v1.ImageContent.getDefaultInstance()) {
          kind_ = io.cyrene.proto.message.connector.v1.ImageContent.newBuilder((io.cyrene.proto.message.connector.v1.ImageContent) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 3) {
          imageBuilder_.mergeFrom(value);
        } else {
          imageBuilder_.setMessage(value);
        }
      }
      kindCase_ = 3;
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.ImageContent image = 3;</code>
     */
    public Builder clearImage() {
      if (imageBuilder_ == null) {
        if (kindCase_ == 3) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 3) {
          kindCase_ = 0;
          kind_ = null;
        }
        imageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.ImageContent image = 3;</code>
     */
    public io.cyrene.proto.message.connector.v1.ImageContent.Builder getImageBuilder() {
      return getImageFieldBuilder().getBuilder();
    }
    /**
     * <code>.cyrene.message.connector.v1.ImageContent image = 3;</code>
     */
    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.ImageContentOrBuilder getImageOrBuilder() {
      if ((kindCase_ == 3) && (imageBuilder_ != null)) {
        return imageBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 3) {
          return (io.cyrene.proto.message.connector.v1.ImageContent) kind_;
        }
        return io.cyrene.proto.message.connector.v1.ImageContent.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.message.connector.v1.ImageContent image = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.proto.message.connector.v1.ImageContent, io.cyrene.proto.message.connector.v1.ImageContent.Builder, io.cyrene.proto.message.connector.v1.ImageContentOrBuilder> 
        getImageFieldBuilder() {
      if (imageBuilder_ == null) {
        if (!(kindCase_ == 3)) {
          kind_ = io.cyrene.proto.message.connector.v1.ImageContent.getDefaultInstance();
        }
        imageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.cyrene.proto.message.connector.v1.ImageContent, io.cyrene.proto.message.connector.v1.ImageContent.Builder, io.cyrene.proto.message.connector.v1.ImageContentOrBuilder>(
                (io.cyrene.proto.message.connector.v1.ImageContent) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 3;
      onChanged();
      return imageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.proto.message.connector.v1.FileContent, io.cyrene.proto.message.connector.v1.FileContent.Builder, io.cyrene.proto.message.connector.v1.FileContentOrBuilder> fileBuilder_;
    /**
     * <code>.cyrene.message.connector.v1.FileContent file = 4;</code>
     * @return Whether the file field is set.
     */
    @java.lang.Override
    public boolean hasFile() {
      return kindCase_ == 4;
    }
    /**
     * <code>.cyrene.message.connector.v1.FileContent file = 4;</code>
     * @return The file.
     */
    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.FileContent getFile() {
      if (fileBuilder_ == null) {
        if (kindCase_ == 4) {
          return (io.cyrene.proto.message.connector.v1.FileContent) kind_;
        }
        return io.cyrene.proto.message.connector.v1.FileContent.getDefaultInstance();
      } else {
        if (kindCase_ == 4) {
          return fileBuilder_.getMessage();
        }
        return io.cyrene.proto.message.connector.v1.FileContent.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.message.connector.v1.FileContent file = 4;</code>
     */
    public Builder setFile(io.cyrene.proto.message.connector.v1.FileContent value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        fileBuilder_.setMessage(value);
      }
      kindCase_ = 4;
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.FileContent file = 4;</code>
     */
    public Builder setFile(
        io.cyrene.proto.message.connector.v1.FileContent.Builder builderForValue) {
      if (fileBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        fileBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 4;
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.FileContent file = 4;</code>
     */
    public Builder mergeFile(io.cyrene.proto.message.connector.v1.FileContent value) {
      if (fileBuilder_ == null) {
        if (kindCase_ == 4 &&
            kind_ != io.cyrene.proto.message.connector.v1.FileContent.getDefaultInstance()) {
          kind_ = io.cyrene.proto.message.connector.v1.FileContent.newBuilder((io.cyrene.proto.message.connector.v1.FileContent) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 4) {
          fileBuilder_.mergeFrom(value);
        } else {
          fileBuilder_.setMessage(value);
        }
      }
      kindCase_ = 4;
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.FileContent file = 4;</code>
     */
    public Builder clearFile() {
      if (fileBuilder_ == null) {
        if (kindCase_ == 4) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 4) {
          kindCase_ = 0;
          kind_ = null;
        }
        fileBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.cyrene.message.connector.v1.FileContent file = 4;</code>
     */
    public io.cyrene.proto.message.connector.v1.FileContent.Builder getFileBuilder() {
      return getFileFieldBuilder().getBuilder();
    }
    /**
     * <code>.cyrene.message.connector.v1.FileContent file = 4;</code>
     */
    @java.lang.Override
    public io.cyrene.proto.message.connector.v1.FileContentOrBuilder getFileOrBuilder() {
      if ((kindCase_ == 4) && (fileBuilder_ != null)) {
        return fileBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 4) {
          return (io.cyrene.proto.message.connector.v1.FileContent) kind_;
        }
        return io.cyrene.proto.message.connector.v1.FileContent.getDefaultInstance();
      }
    }
    /**
     * <code>.cyrene.message.connector.v1.FileContent file = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.proto.message.connector.v1.FileContent, io.cyrene.proto.message.connector.v1.FileContent.Builder, io.cyrene.proto.message.connector.v1.FileContentOrBuilder> 
        getFileFieldBuilder() {
      if (fileBuilder_ == null) {
        if (!(kindCase_ == 4)) {
          kind_ = io.cyrene.proto.message.connector.v1.FileContent.getDefaultInstance();
        }
        fileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.cyrene.proto.message.connector.v1.FileContent, io.cyrene.proto.message.connector.v1.FileContent.Builder, io.cyrene.proto.message.connector.v1.FileContentOrBuilder>(
                (io.cyrene.proto.message.connector.v1.FileContent) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 4;
      onChanged();
      return fileBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cyrene.message.connector.v1.MessageContentPart)
  }

  // @@protoc_insertion_point(class_scope:cyrene.message.connector.v1.MessageContentPart)
  private static final io.cyrene.proto.message.connector.v1.MessageContentPart DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.cyrene.proto.message.connector.v1.MessageContentPart();
  }

  public static io.cyrene.proto.message.connector.v1.MessageContentPart getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageContentPart>
      PARSER = new com.google.protobuf.AbstractParser<MessageContentPart>() {
    @java.lang.Override
    public MessageContentPart parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MessageContentPart> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageContentPart> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.cyrene.proto.message.connector.v1.MessageContentPart getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

