// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/message/connector/v1/message_connector.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.message.connector.v1;

public interface SendMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cyrene.message.connector.v1.SendMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.cyrene.message.connector.v1.ConversationScope conversation = 1;</code>
   * @return Whether the conversation field is set.
   */
  boolean hasConversation();
  /**
   * <code>.cyrene.message.connector.v1.ConversationScope conversation = 1;</code>
   * @return The conversation.
   */
  io.cyrene.proto.message.connector.v1.ConversationScope getConversation();
  /**
   * <code>.cyrene.message.connector.v1.ConversationScope conversation = 1;</code>
   */
  io.cyrene.proto.message.connector.v1.ConversationScopeOrBuilder getConversationOrBuilder();

  /**
   * <code>repeated .cyrene.message.connector.v1.MessageContentPart content = 2;</code>
   */
  java.util.List<io.cyrene.proto.message.connector.v1.MessageContentPart> 
      getContentList();
  /**
   * <code>repeated .cyrene.message.connector.v1.MessageContentPart content = 2;</code>
   */
  io.cyrene.proto.message.connector.v1.MessageContentPart getContent(int index);
  /**
   * <code>repeated .cyrene.message.connector.v1.MessageContentPart content = 2;</code>
   */
  int getContentCount();
  /**
   * <code>repeated .cyrene.message.connector.v1.MessageContentPart content = 2;</code>
   */
  java.util.List<? extends io.cyrene.proto.message.connector.v1.MessageContentPartOrBuilder> 
      getContentOrBuilderList();
  /**
   * <code>repeated .cyrene.message.connector.v1.MessageContentPart content = 2;</code>
   */
  io.cyrene.proto.message.connector.v1.MessageContentPartOrBuilder getContentOrBuilder(
      int index);

  /**
   * <code>.cyrene.message.connector.v1.ReplyReference reply = 3;</code>
   * @return Whether the reply field is set.
   */
  boolean hasReply();
  /**
   * <code>.cyrene.message.connector.v1.ReplyReference reply = 3;</code>
   * @return The reply.
   */
  io.cyrene.proto.message.connector.v1.ReplyReference getReply();
  /**
   * <code>.cyrene.message.connector.v1.ReplyReference reply = 3;</code>
   */
  io.cyrene.proto.message.connector.v1.ReplyReferenceOrBuilder getReplyOrBuilder();

  /**
   * <code>.cyrene.message.connector.v1.VendorExtension vendor_extension = 4;</code>
   * @return Whether the vendorExtension field is set.
   */
  boolean hasVendorExtension();
  /**
   * <code>.cyrene.message.connector.v1.VendorExtension vendor_extension = 4;</code>
   * @return The vendorExtension.
   */
  io.cyrene.proto.message.connector.v1.VendorExtension getVendorExtension();
  /**
   * <code>.cyrene.message.connector.v1.VendorExtension vendor_extension = 4;</code>
   */
  io.cyrene.proto.message.connector.v1.VendorExtensionOrBuilder getVendorExtensionOrBuilder();
}
