// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/agent/runtime/v1/agent_runtime.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.agent.runtime.v1;

public interface AgentRunErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cyrene.agent.runtime.v1.AgentRunError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.cyrene.agent.runtime.v1.AgentErrorCode code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.cyrene.agent.runtime.v1.AgentErrorCode code = 1;</code>
   * @return The code.
   */
  io.cyrene.proto.agent.runtime.v1.AgentErrorCode getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>bool retryable = 3;</code>
   * @return The retryable.
   */
  boolean getRetryable();

  /**
   * <code>string domain_details = 4;</code>
   * @return The domainDetails.
   */
  java.lang.String getDomainDetails();
  /**
   * <code>string domain_details = 4;</code>
   * @return The bytes for domainDetails.
   */
  com.google.protobuf.ByteString
      getDomainDetailsBytes();
}
