// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/agent/runtime/v1/agent_runtime.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.agent.runtime.v1;

/**
 * Protobuf type {@code cyrene.agent.runtime.v1.ToolCallCompletedEvent}
 */
public final class ToolCallCompletedEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cyrene.agent.runtime.v1.ToolCallCompletedEvent)
    ToolCallCompletedEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ToolCallCompletedEvent.newBuilder() to construct.
  private ToolCallCompletedEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ToolCallCompletedEvent() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ToolCallCompletedEvent();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.cyrene.proto.agent.runtime.v1.AgentRuntimeProto.internal_static_cyrene_agent_runtime_v1_ToolCallCompletedEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.cyrene.proto.agent.runtime.v1.AgentRuntimeProto.internal_static_cyrene_agent_runtime_v1_ToolCallCompletedEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent.class, io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent.Builder.class);
  }

  private int bitField0_;
  public static final int RESULT_FIELD_NUMBER = 1;
  private io.cyrene.proto.agent.runtime.v1.ToolCallResult result_;
  /**
   * <code>.cyrene.agent.runtime.v1.ToolCallResult result = 1;</code>
   * @return Whether the result field is set.
   */
  @java.lang.Override
  public boolean hasResult() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.cyrene.agent.runtime.v1.ToolCallResult result = 1;</code>
   * @return The result.
   */
  @java.lang.Override
  public io.cyrene.proto.agent.runtime.v1.ToolCallResult getResult() {
    return result_ == null ? io.cyrene.proto.agent.runtime.v1.ToolCallResult.getDefaultInstance() : result_;
  }
  /**
   * <code>.cyrene.agent.runtime.v1.ToolCallResult result = 1;</code>
   */
  @java.lang.Override
  public io.cyrene.proto.agent.runtime.v1.ToolCallResultOrBuilder getResultOrBuilder() {
    return result_ == null ? io.cyrene.proto.agent.runtime.v1.ToolCallResult.getDefaultInstance() : result_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getResult());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResult());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent)) {
      return super.equals(obj);
    }
    io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent other = (io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent) obj;

    if (hasResult() != other.hasResult()) return false;
    if (hasResult()) {
      if (!getResult()
          .equals(other.getResult())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResult()) {
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cyrene.agent.runtime.v1.ToolCallCompletedEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cyrene.agent.runtime.v1.ToolCallCompletedEvent)
      io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.cyrene.proto.agent.runtime.v1.AgentRuntimeProto.internal_static_cyrene_agent_runtime_v1_ToolCallCompletedEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.cyrene.proto.agent.runtime.v1.AgentRuntimeProto.internal_static_cyrene_agent_runtime_v1_ToolCallCompletedEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent.class, io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent.Builder.class);
    }

    // Construct using io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      result_ = null;
      if (resultBuilder_ != null) {
        resultBuilder_.dispose();
        resultBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.cyrene.proto.agent.runtime.v1.AgentRuntimeProto.internal_static_cyrene_agent_runtime_v1_ToolCallCompletedEvent_descriptor;
    }

    @java.lang.Override
    public io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent getDefaultInstanceForType() {
      return io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent.getDefaultInstance();
    }

    @java.lang.Override
    public io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent build() {
      io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent buildPartial() {
      io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent result = new io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.result_ = resultBuilder_ == null
            ? result_
            : resultBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent) {
        return mergeFrom((io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent other) {
      if (other == io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent.getDefaultInstance()) return this;
      if (other.hasResult()) {
        mergeResult(other.getResult());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getResultFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.cyrene.proto.agent.runtime.v1.ToolCallResult result_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.proto.agent.runtime.v1.ToolCallResult, io.cyrene.proto.agent.runtime.v1.ToolCallResult.Builder, io.cyrene.proto.agent.runtime.v1.ToolCallResultOrBuilder> resultBuilder_;
    /**
     * <code>.cyrene.agent.runtime.v1.ToolCallResult result = 1;</code>
     * @return Whether the result field is set.
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.cyrene.agent.runtime.v1.ToolCallResult result = 1;</code>
     * @return The result.
     */
    public io.cyrene.proto.agent.runtime.v1.ToolCallResult getResult() {
      if (resultBuilder_ == null) {
        return result_ == null ? io.cyrene.proto.agent.runtime.v1.ToolCallResult.getDefaultInstance() : result_;
      } else {
        return resultBuilder_.getMessage();
      }
    }
    /**
     * <code>.cyrene.agent.runtime.v1.ToolCallResult result = 1;</code>
     */
    public Builder setResult(io.cyrene.proto.agent.runtime.v1.ToolCallResult value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
      } else {
        resultBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.cyrene.agent.runtime.v1.ToolCallResult result = 1;</code>
     */
    public Builder setResult(
        io.cyrene.proto.agent.runtime.v1.ToolCallResult.Builder builderForValue) {
      if (resultBuilder_ == null) {
        result_ = builderForValue.build();
      } else {
        resultBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.cyrene.agent.runtime.v1.ToolCallResult result = 1;</code>
     */
    public Builder mergeResult(io.cyrene.proto.agent.runtime.v1.ToolCallResult value) {
      if (resultBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          result_ != null &&
          result_ != io.cyrene.proto.agent.runtime.v1.ToolCallResult.getDefaultInstance()) {
          getResultBuilder().mergeFrom(value);
        } else {
          result_ = value;
        }
      } else {
        resultBuilder_.mergeFrom(value);
      }
      if (result_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.cyrene.agent.runtime.v1.ToolCallResult result = 1;</code>
     */
    public Builder clearResult() {
      bitField0_ = (bitField0_ & ~0x00000001);
      result_ = null;
      if (resultBuilder_ != null) {
        resultBuilder_.dispose();
        resultBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.cyrene.agent.runtime.v1.ToolCallResult result = 1;</code>
     */
    public io.cyrene.proto.agent.runtime.v1.ToolCallResult.Builder getResultBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.cyrene.agent.runtime.v1.ToolCallResult result = 1;</code>
     */
    public io.cyrene.proto.agent.runtime.v1.ToolCallResultOrBuilder getResultOrBuilder() {
      if (resultBuilder_ != null) {
        return resultBuilder_.getMessageOrBuilder();
      } else {
        return result_ == null ?
            io.cyrene.proto.agent.runtime.v1.ToolCallResult.getDefaultInstance() : result_;
      }
    }
    /**
     * <code>.cyrene.agent.runtime.v1.ToolCallResult result = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.proto.agent.runtime.v1.ToolCallResult, io.cyrene.proto.agent.runtime.v1.ToolCallResult.Builder, io.cyrene.proto.agent.runtime.v1.ToolCallResultOrBuilder> 
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.cyrene.proto.agent.runtime.v1.ToolCallResult, io.cyrene.proto.agent.runtime.v1.ToolCallResult.Builder, io.cyrene.proto.agent.runtime.v1.ToolCallResultOrBuilder>(
                getResult(),
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      return resultBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cyrene.agent.runtime.v1.ToolCallCompletedEvent)
  }

  // @@protoc_insertion_point(class_scope:cyrene.agent.runtime.v1.ToolCallCompletedEvent)
  private static final io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent();
  }

  public static io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ToolCallCompletedEvent>
      PARSER = new com.google.protobuf.AbstractParser<ToolCallCompletedEvent>() {
    @java.lang.Override
    public ToolCallCompletedEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ToolCallCompletedEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ToolCallCompletedEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.cyrene.proto.agent.runtime.v1.ToolCallCompletedEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

