// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/agent/runtime/v1/agent_runtime.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.agent.runtime.v1;

/**
 * Protobuf type {@code cyrene.agent.runtime.v1.UsageStats}
 */
public final class UsageStats extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cyrene.agent.runtime.v1.UsageStats)
    UsageStatsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UsageStats.newBuilder() to construct.
  private UsageStats(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UsageStats() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UsageStats();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.cyrene.proto.agent.runtime.v1.AgentRuntimeProto.internal_static_cyrene_agent_runtime_v1_UsageStats_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.cyrene.proto.agent.runtime.v1.AgentRuntimeProto.internal_static_cyrene_agent_runtime_v1_UsageStats_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.cyrene.proto.agent.runtime.v1.UsageStats.class, io.cyrene.proto.agent.runtime.v1.UsageStats.Builder.class);
  }

  public static final int PROMPT_TOKENS_FIELD_NUMBER = 1;
  private int promptTokens_ = 0;
  /**
   * <code>int32 prompt_tokens = 1;</code>
   * @return The promptTokens.
   */
  @java.lang.Override
  public int getPromptTokens() {
    return promptTokens_;
  }

  public static final int COMPLETION_TOKENS_FIELD_NUMBER = 2;
  private int completionTokens_ = 0;
  /**
   * <code>int32 completion_tokens = 2;</code>
   * @return The completionTokens.
   */
  @java.lang.Override
  public int getCompletionTokens() {
    return completionTokens_;
  }

  public static final int TOTAL_TOKENS_FIELD_NUMBER = 3;
  private int totalTokens_ = 0;
  /**
   * <code>int32 total_tokens = 3;</code>
   * @return The totalTokens.
   */
  @java.lang.Override
  public int getTotalTokens() {
    return totalTokens_;
  }

  public static final int MODEL_CALL_COUNT_FIELD_NUMBER = 4;
  private int modelCallCount_ = 0;
  /**
   * <code>int32 model_call_count = 4;</code>
   * @return The modelCallCount.
   */
  @java.lang.Override
  public int getModelCallCount() {
    return modelCallCount_;
  }

  public static final int TOOL_CALL_COUNT_FIELD_NUMBER = 5;
  private int toolCallCount_ = 0;
  /**
   * <code>int32 tool_call_count = 5;</code>
   * @return The toolCallCount.
   */
  @java.lang.Override
  public int getToolCallCount() {
    return toolCallCount_;
  }

  public static final int EXECUTION_DURATION_MS_FIELD_NUMBER = 6;
  private long executionDurationMs_ = 0L;
  /**
   * <code>int64 execution_duration_ms = 6;</code>
   * @return The executionDurationMs.
   */
  @java.lang.Override
  public long getExecutionDurationMs() {
    return executionDurationMs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (promptTokens_ != 0) {
      output.writeInt32(1, promptTokens_);
    }
    if (completionTokens_ != 0) {
      output.writeInt32(2, completionTokens_);
    }
    if (totalTokens_ != 0) {
      output.writeInt32(3, totalTokens_);
    }
    if (modelCallCount_ != 0) {
      output.writeInt32(4, modelCallCount_);
    }
    if (toolCallCount_ != 0) {
      output.writeInt32(5, toolCallCount_);
    }
    if (executionDurationMs_ != 0L) {
      output.writeInt64(6, executionDurationMs_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (promptTokens_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, promptTokens_);
    }
    if (completionTokens_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, completionTokens_);
    }
    if (totalTokens_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, totalTokens_);
    }
    if (modelCallCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, modelCallCount_);
    }
    if (toolCallCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, toolCallCount_);
    }
    if (executionDurationMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, executionDurationMs_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.cyrene.proto.agent.runtime.v1.UsageStats)) {
      return super.equals(obj);
    }
    io.cyrene.proto.agent.runtime.v1.UsageStats other = (io.cyrene.proto.agent.runtime.v1.UsageStats) obj;

    if (getPromptTokens()
        != other.getPromptTokens()) return false;
    if (getCompletionTokens()
        != other.getCompletionTokens()) return false;
    if (getTotalTokens()
        != other.getTotalTokens()) return false;
    if (getModelCallCount()
        != other.getModelCallCount()) return false;
    if (getToolCallCount()
        != other.getToolCallCount()) return false;
    if (getExecutionDurationMs()
        != other.getExecutionDurationMs()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROMPT_TOKENS_FIELD_NUMBER;
    hash = (53 * hash) + getPromptTokens();
    hash = (37 * hash) + COMPLETION_TOKENS_FIELD_NUMBER;
    hash = (53 * hash) + getCompletionTokens();
    hash = (37 * hash) + TOTAL_TOKENS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalTokens();
    hash = (37 * hash) + MODEL_CALL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getModelCallCount();
    hash = (37 * hash) + TOOL_CALL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getToolCallCount();
    hash = (37 * hash) + EXECUTION_DURATION_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExecutionDurationMs());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.cyrene.proto.agent.runtime.v1.UsageStats parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.agent.runtime.v1.UsageStats parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.agent.runtime.v1.UsageStats parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.agent.runtime.v1.UsageStats parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.agent.runtime.v1.UsageStats parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.agent.runtime.v1.UsageStats parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.agent.runtime.v1.UsageStats parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.agent.runtime.v1.UsageStats parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.cyrene.proto.agent.runtime.v1.UsageStats parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.cyrene.proto.agent.runtime.v1.UsageStats parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.cyrene.proto.agent.runtime.v1.UsageStats parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.agent.runtime.v1.UsageStats parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.cyrene.proto.agent.runtime.v1.UsageStats prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cyrene.agent.runtime.v1.UsageStats}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cyrene.agent.runtime.v1.UsageStats)
      io.cyrene.proto.agent.runtime.v1.UsageStatsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.cyrene.proto.agent.runtime.v1.AgentRuntimeProto.internal_static_cyrene_agent_runtime_v1_UsageStats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.cyrene.proto.agent.runtime.v1.AgentRuntimeProto.internal_static_cyrene_agent_runtime_v1_UsageStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.cyrene.proto.agent.runtime.v1.UsageStats.class, io.cyrene.proto.agent.runtime.v1.UsageStats.Builder.class);
    }

    // Construct using io.cyrene.proto.agent.runtime.v1.UsageStats.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      promptTokens_ = 0;
      completionTokens_ = 0;
      totalTokens_ = 0;
      modelCallCount_ = 0;
      toolCallCount_ = 0;
      executionDurationMs_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.cyrene.proto.agent.runtime.v1.AgentRuntimeProto.internal_static_cyrene_agent_runtime_v1_UsageStats_descriptor;
    }

    @java.lang.Override
    public io.cyrene.proto.agent.runtime.v1.UsageStats getDefaultInstanceForType() {
      return io.cyrene.proto.agent.runtime.v1.UsageStats.getDefaultInstance();
    }

    @java.lang.Override
    public io.cyrene.proto.agent.runtime.v1.UsageStats build() {
      io.cyrene.proto.agent.runtime.v1.UsageStats result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.cyrene.proto.agent.runtime.v1.UsageStats buildPartial() {
      io.cyrene.proto.agent.runtime.v1.UsageStats result = new io.cyrene.proto.agent.runtime.v1.UsageStats(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.cyrene.proto.agent.runtime.v1.UsageStats result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.promptTokens_ = promptTokens_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.completionTokens_ = completionTokens_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalTokens_ = totalTokens_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.modelCallCount_ = modelCallCount_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.toolCallCount_ = toolCallCount_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.executionDurationMs_ = executionDurationMs_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.cyrene.proto.agent.runtime.v1.UsageStats) {
        return mergeFrom((io.cyrene.proto.agent.runtime.v1.UsageStats)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.cyrene.proto.agent.runtime.v1.UsageStats other) {
      if (other == io.cyrene.proto.agent.runtime.v1.UsageStats.getDefaultInstance()) return this;
      if (other.getPromptTokens() != 0) {
        setPromptTokens(other.getPromptTokens());
      }
      if (other.getCompletionTokens() != 0) {
        setCompletionTokens(other.getCompletionTokens());
      }
      if (other.getTotalTokens() != 0) {
        setTotalTokens(other.getTotalTokens());
      }
      if (other.getModelCallCount() != 0) {
        setModelCallCount(other.getModelCallCount());
      }
      if (other.getToolCallCount() != 0) {
        setToolCallCount(other.getToolCallCount());
      }
      if (other.getExecutionDurationMs() != 0L) {
        setExecutionDurationMs(other.getExecutionDurationMs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              promptTokens_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              completionTokens_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              totalTokens_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              modelCallCount_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              toolCallCount_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              executionDurationMs_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int promptTokens_ ;
    /**
     * <code>int32 prompt_tokens = 1;</code>
     * @return The promptTokens.
     */
    @java.lang.Override
    public int getPromptTokens() {
      return promptTokens_;
    }
    /**
     * <code>int32 prompt_tokens = 1;</code>
     * @param value The promptTokens to set.
     * @return This builder for chaining.
     */
    public Builder setPromptTokens(int value) {

      promptTokens_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 prompt_tokens = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPromptTokens() {
      bitField0_ = (bitField0_ & ~0x00000001);
      promptTokens_ = 0;
      onChanged();
      return this;
    }

    private int completionTokens_ ;
    /**
     * <code>int32 completion_tokens = 2;</code>
     * @return The completionTokens.
     */
    @java.lang.Override
    public int getCompletionTokens() {
      return completionTokens_;
    }
    /**
     * <code>int32 completion_tokens = 2;</code>
     * @param value The completionTokens to set.
     * @return This builder for chaining.
     */
    public Builder setCompletionTokens(int value) {

      completionTokens_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 completion_tokens = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompletionTokens() {
      bitField0_ = (bitField0_ & ~0x00000002);
      completionTokens_ = 0;
      onChanged();
      return this;
    }

    private int totalTokens_ ;
    /**
     * <code>int32 total_tokens = 3;</code>
     * @return The totalTokens.
     */
    @java.lang.Override
    public int getTotalTokens() {
      return totalTokens_;
    }
    /**
     * <code>int32 total_tokens = 3;</code>
     * @param value The totalTokens to set.
     * @return This builder for chaining.
     */
    public Builder setTotalTokens(int value) {

      totalTokens_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_tokens = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalTokens() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalTokens_ = 0;
      onChanged();
      return this;
    }

    private int modelCallCount_ ;
    /**
     * <code>int32 model_call_count = 4;</code>
     * @return The modelCallCount.
     */
    @java.lang.Override
    public int getModelCallCount() {
      return modelCallCount_;
    }
    /**
     * <code>int32 model_call_count = 4;</code>
     * @param value The modelCallCount to set.
     * @return This builder for chaining.
     */
    public Builder setModelCallCount(int value) {

      modelCallCount_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 model_call_count = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearModelCallCount() {
      bitField0_ = (bitField0_ & ~0x00000008);
      modelCallCount_ = 0;
      onChanged();
      return this;
    }

    private int toolCallCount_ ;
    /**
     * <code>int32 tool_call_count = 5;</code>
     * @return The toolCallCount.
     */
    @java.lang.Override
    public int getToolCallCount() {
      return toolCallCount_;
    }
    /**
     * <code>int32 tool_call_count = 5;</code>
     * @param value The toolCallCount to set.
     * @return This builder for chaining.
     */
    public Builder setToolCallCount(int value) {

      toolCallCount_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tool_call_count = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearToolCallCount() {
      bitField0_ = (bitField0_ & ~0x00000010);
      toolCallCount_ = 0;
      onChanged();
      return this;
    }

    private long executionDurationMs_ ;
    /**
     * <code>int64 execution_duration_ms = 6;</code>
     * @return The executionDurationMs.
     */
    @java.lang.Override
    public long getExecutionDurationMs() {
      return executionDurationMs_;
    }
    /**
     * <code>int64 execution_duration_ms = 6;</code>
     * @param value The executionDurationMs to set.
     * @return This builder for chaining.
     */
    public Builder setExecutionDurationMs(long value) {

      executionDurationMs_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 execution_duration_ms = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecutionDurationMs() {
      bitField0_ = (bitField0_ & ~0x00000020);
      executionDurationMs_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cyrene.agent.runtime.v1.UsageStats)
  }

  // @@protoc_insertion_point(class_scope:cyrene.agent.runtime.v1.UsageStats)
  private static final io.cyrene.proto.agent.runtime.v1.UsageStats DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.cyrene.proto.agent.runtime.v1.UsageStats();
  }

  public static io.cyrene.proto.agent.runtime.v1.UsageStats getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UsageStats>
      PARSER = new com.google.protobuf.AbstractParser<UsageStats>() {
    @java.lang.Override
    public UsageStats parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UsageStats> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UsageStats> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.cyrene.proto.agent.runtime.v1.UsageStats getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

