// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/computer/runtime/v1/computer_runtime.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.computer.runtime.v1;

/**
 * Protobuf type {@code cyrene.computer.runtime.v1.ArtifactPayload}
 */
public final class ArtifactPayload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cyrene.computer.runtime.v1.ArtifactPayload)
    ArtifactPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ArtifactPayload.newBuilder() to construct.
  private ArtifactPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ArtifactPayload() {
    data_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ArtifactPayload();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.cyrene.proto.computer.runtime.v1.ComputerRuntimeProto.internal_static_cyrene_computer_runtime_v1_ArtifactPayload_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.cyrene.proto.computer.runtime.v1.ComputerRuntimeProto.internal_static_cyrene_computer_runtime_v1_ArtifactPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.cyrene.proto.computer.runtime.v1.ArtifactPayload.class, io.cyrene.proto.computer.runtime.v1.ArtifactPayload.Builder.class);
  }

  private int bitField0_;
  public static final int METADATA_FIELD_NUMBER = 1;
  private io.cyrene.proto.computer.runtime.v1.ArtifactMetadata metadata_;
  /**
   * <code>.cyrene.computer.runtime.v1.ArtifactMetadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.cyrene.computer.runtime.v1.ArtifactMetadata metadata = 1;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public io.cyrene.proto.computer.runtime.v1.ArtifactMetadata getMetadata() {
    return metadata_ == null ? io.cyrene.proto.computer.runtime.v1.ArtifactMetadata.getDefaultInstance() : metadata_;
  }
  /**
   * <code>.cyrene.computer.runtime.v1.ArtifactMetadata metadata = 1;</code>
   */
  @java.lang.Override
  public io.cyrene.proto.computer.runtime.v1.ArtifactMetadataOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? io.cyrene.proto.computer.runtime.v1.ArtifactMetadata.getDefaultInstance() : metadata_;
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getMetadata());
    }
    if (!data_.isEmpty()) {
      output.writeBytes(2, data_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMetadata());
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, data_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.cyrene.proto.computer.runtime.v1.ArtifactPayload)) {
      return super.equals(obj);
    }
    io.cyrene.proto.computer.runtime.v1.ArtifactPayload other = (io.cyrene.proto.computer.runtime.v1.ArtifactPayload) obj;

    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!getData()
        .equals(other.getData())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.cyrene.proto.computer.runtime.v1.ArtifactPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.computer.runtime.v1.ArtifactPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.computer.runtime.v1.ArtifactPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.computer.runtime.v1.ArtifactPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.computer.runtime.v1.ArtifactPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.computer.runtime.v1.ArtifactPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.computer.runtime.v1.ArtifactPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.computer.runtime.v1.ArtifactPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.cyrene.proto.computer.runtime.v1.ArtifactPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.cyrene.proto.computer.runtime.v1.ArtifactPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.cyrene.proto.computer.runtime.v1.ArtifactPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.computer.runtime.v1.ArtifactPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.cyrene.proto.computer.runtime.v1.ArtifactPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cyrene.computer.runtime.v1.ArtifactPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cyrene.computer.runtime.v1.ArtifactPayload)
      io.cyrene.proto.computer.runtime.v1.ArtifactPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.cyrene.proto.computer.runtime.v1.ComputerRuntimeProto.internal_static_cyrene_computer_runtime_v1_ArtifactPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.cyrene.proto.computer.runtime.v1.ComputerRuntimeProto.internal_static_cyrene_computer_runtime_v1_ArtifactPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.cyrene.proto.computer.runtime.v1.ArtifactPayload.class, io.cyrene.proto.computer.runtime.v1.ArtifactPayload.Builder.class);
    }

    // Construct using io.cyrene.proto.computer.runtime.v1.ArtifactPayload.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMetadataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      data_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.cyrene.proto.computer.runtime.v1.ComputerRuntimeProto.internal_static_cyrene_computer_runtime_v1_ArtifactPayload_descriptor;
    }

    @java.lang.Override
    public io.cyrene.proto.computer.runtime.v1.ArtifactPayload getDefaultInstanceForType() {
      return io.cyrene.proto.computer.runtime.v1.ArtifactPayload.getDefaultInstance();
    }

    @java.lang.Override
    public io.cyrene.proto.computer.runtime.v1.ArtifactPayload build() {
      io.cyrene.proto.computer.runtime.v1.ArtifactPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.cyrene.proto.computer.runtime.v1.ArtifactPayload buildPartial() {
      io.cyrene.proto.computer.runtime.v1.ArtifactPayload result = new io.cyrene.proto.computer.runtime.v1.ArtifactPayload(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.cyrene.proto.computer.runtime.v1.ArtifactPayload result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.data_ = data_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.cyrene.proto.computer.runtime.v1.ArtifactPayload) {
        return mergeFrom((io.cyrene.proto.computer.runtime.v1.ArtifactPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.cyrene.proto.computer.runtime.v1.ArtifactPayload other) {
      if (other == io.cyrene.proto.computer.runtime.v1.ArtifactPayload.getDefaultInstance()) return this;
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              data_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.cyrene.proto.computer.runtime.v1.ArtifactMetadata metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.proto.computer.runtime.v1.ArtifactMetadata, io.cyrene.proto.computer.runtime.v1.ArtifactMetadata.Builder, io.cyrene.proto.computer.runtime.v1.ArtifactMetadataOrBuilder> metadataBuilder_;
    /**
     * <code>.cyrene.computer.runtime.v1.ArtifactMetadata metadata = 1;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.cyrene.computer.runtime.v1.ArtifactMetadata metadata = 1;</code>
     * @return The metadata.
     */
    public io.cyrene.proto.computer.runtime.v1.ArtifactMetadata getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? io.cyrene.proto.computer.runtime.v1.ArtifactMetadata.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <code>.cyrene.computer.runtime.v1.ArtifactMetadata metadata = 1;</code>
     */
    public Builder setMetadata(io.cyrene.proto.computer.runtime.v1.ArtifactMetadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.cyrene.computer.runtime.v1.ArtifactMetadata metadata = 1;</code>
     */
    public Builder setMetadata(
        io.cyrene.proto.computer.runtime.v1.ArtifactMetadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.cyrene.computer.runtime.v1.ArtifactMetadata metadata = 1;</code>
     */
    public Builder mergeMetadata(io.cyrene.proto.computer.runtime.v1.ArtifactMetadata value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          metadata_ != null &&
          metadata_ != io.cyrene.proto.computer.runtime.v1.ArtifactMetadata.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      if (metadata_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.cyrene.computer.runtime.v1.ArtifactMetadata metadata = 1;</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000001);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.cyrene.computer.runtime.v1.ArtifactMetadata metadata = 1;</code>
     */
    public io.cyrene.proto.computer.runtime.v1.ArtifactMetadata.Builder getMetadataBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>.cyrene.computer.runtime.v1.ArtifactMetadata metadata = 1;</code>
     */
    public io.cyrene.proto.computer.runtime.v1.ArtifactMetadataOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            io.cyrene.proto.computer.runtime.v1.ArtifactMetadata.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <code>.cyrene.computer.runtime.v1.ArtifactMetadata metadata = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.cyrene.proto.computer.runtime.v1.ArtifactMetadata, io.cyrene.proto.computer.runtime.v1.ArtifactMetadata.Builder, io.cyrene.proto.computer.runtime.v1.ArtifactMetadataOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.cyrene.proto.computer.runtime.v1.ArtifactMetadata, io.cyrene.proto.computer.runtime.v1.ArtifactMetadata.Builder, io.cyrene.proto.computer.runtime.v1.ArtifactMetadataOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>bytes data = 2;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      data_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bytes data = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000002);
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cyrene.computer.runtime.v1.ArtifactPayload)
  }

  // @@protoc_insertion_point(class_scope:cyrene.computer.runtime.v1.ArtifactPayload)
  private static final io.cyrene.proto.computer.runtime.v1.ArtifactPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.cyrene.proto.computer.runtime.v1.ArtifactPayload();
  }

  public static io.cyrene.proto.computer.runtime.v1.ArtifactPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ArtifactPayload>
      PARSER = new com.google.protobuf.AbstractParser<ArtifactPayload>() {
    @java.lang.Override
    public ArtifactPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ArtifactPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ArtifactPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.cyrene.proto.computer.runtime.v1.ArtifactPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

