// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/computer/runtime/v1/computer_runtime.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.computer.runtime.v1;

public interface DirEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cyrene.computer.runtime.v1.DirEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool is_directory = 2;</code>
   * @return The isDirectory.
   */
  boolean getIsDirectory();

  /**
   * <code>int64 size_bytes = 3;</code>
   * @return The sizeBytes.
   */
  long getSizeBytes();

  /**
   * <code>int64 modified_at_ms = 4;</code>
   * @return The modifiedAtMs.
   */
  long getModifiedAtMs();
}
