// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/computer/runtime/v1/computer_runtime.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.computer.runtime.v1;

public interface ExecutionEvidenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cyrene.computer.runtime.v1.ExecutionEvidence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 exit_code = 1;</code>
   * @return The exitCode.
   */
  int getExitCode();

  /**
   * <code>int64 duration_ms = 2;</code>
   * @return The durationMs.
   */
  long getDurationMs();

  /**
   * <code>string stdout = 3;</code>
   * @return The stdout.
   */
  java.lang.String getStdout();
  /**
   * <code>string stdout = 3;</code>
   * @return The bytes for stdout.
   */
  com.google.protobuf.ByteString
      getStdoutBytes();

  /**
   * <code>string stderr = 4;</code>
   * @return The stderr.
   */
  java.lang.String getStderr();
  /**
   * <code>string stderr = 4;</code>
   * @return The bytes for stderr.
   */
  com.google.protobuf.ByteString
      getStderrBytes();

  /**
   * <code>bool stdout_truncated = 5;</code>
   * @return The stdoutTruncated.
   */
  boolean getStdoutTruncated();

  /**
   * <code>bool stderr_truncated = 6;</code>
   * @return The stderrTruncated.
   */
  boolean getStderrTruncated();

  /**
   * <code>string sha256_hash = 7;</code>
   * @return The sha256Hash.
   */
  java.lang.String getSha256Hash();
  /**
   * <code>string sha256_hash = 7;</code>
   * @return The bytes for sha256Hash.
   */
  com.google.protobuf.ByteString
      getSha256HashBytes();

  /**
   * <code>optional .cyrene.computer.runtime.v1.ExecutionResourceUsage resource_usage = 8;</code>
   * @return Whether the resourceUsage field is set.
   */
  boolean hasResourceUsage();
  /**
   * <code>optional .cyrene.computer.runtime.v1.ExecutionResourceUsage resource_usage = 8;</code>
   * @return The resourceUsage.
   */
  io.cyrene.proto.computer.runtime.v1.ExecutionResourceUsage getResourceUsage();
  /**
   * <code>optional .cyrene.computer.runtime.v1.ExecutionResourceUsage resource_usage = 8;</code>
   */
  io.cyrene.proto.computer.runtime.v1.ExecutionResourceUsageOrBuilder getResourceUsageOrBuilder();
}
