// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/computer/runtime/v1/computer_runtime.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.computer.runtime.v1;

public interface GetArtifactRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cyrene.computer.runtime.v1.GetArtifactRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string artifact_id = 1;</code>
   * @return The artifactId.
   */
  java.lang.String getArtifactId();
  /**
   * <code>string artifact_id = 1;</code>
   * @return The bytes for artifactId.
   */
  com.google.protobuf.ByteString
      getArtifactIdBytes();
}
