// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/model/provider/v1/model_provider.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.model.provider.v1;

public interface ChatToolCallDeltaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cyrene.model.provider.v1.ChatToolCallDelta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 index = 1;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>optional string id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string type = 3;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>optional string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>optional string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>optional string function_name = 4;</code>
   * @return Whether the functionName field is set.
   */
  boolean hasFunctionName();
  /**
   * <code>optional string function_name = 4;</code>
   * @return The functionName.
   */
  java.lang.String getFunctionName();
  /**
   * <code>optional string function_name = 4;</code>
   * @return The bytes for functionName.
   */
  com.google.protobuf.ByteString
      getFunctionNameBytes();

  /**
   * <code>optional string function_arguments = 5;</code>
   * @return Whether the functionArguments field is set.
   */
  boolean hasFunctionArguments();
  /**
   * <code>optional string function_arguments = 5;</code>
   * @return The functionArguments.
   */
  java.lang.String getFunctionArguments();
  /**
   * <code>optional string function_arguments = 5;</code>
   * @return The bytes for functionArguments.
   */
  com.google.protobuf.ByteString
      getFunctionArgumentsBytes();
}
