// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/model/provider/v1/model_provider.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.model.provider.v1;

/**
 * Protobuf type {@code cyrene.model.provider.v1.EmbeddingsRequest}
 */
public final class EmbeddingsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cyrene.model.provider.v1.EmbeddingsRequest)
    EmbeddingsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmbeddingsRequest.newBuilder() to construct.
  private EmbeddingsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmbeddingsRequest() {
    inputs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    model_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EmbeddingsRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.cyrene.proto.model.provider.v1.ModelProviderProto.internal_static_cyrene_model_provider_v1_EmbeddingsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.cyrene.proto.model.provider.v1.ModelProviderProto.internal_static_cyrene_model_provider_v1_EmbeddingsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.cyrene.proto.model.provider.v1.EmbeddingsRequest.class, io.cyrene.proto.model.provider.v1.EmbeddingsRequest.Builder.class);
  }

  private int bitField0_;
  public static final int INPUTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList inputs_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * Ordered text inputs. A request MUST contain at least one item. Empty
   * strings are invalid; whitespace is preserved and is not normalized.
   * </pre>
   *
   * <code>repeated string inputs = 1;</code>
   * @return A list containing the inputs.
   */
  public com.google.protobuf.ProtocolStringList
      getInputsList() {
    return inputs_;
  }
  /**
   * <pre>
   * Ordered text inputs. A request MUST contain at least one item. Empty
   * strings are invalid; whitespace is preserved and is not normalized.
   * </pre>
   *
   * <code>repeated string inputs = 1;</code>
   * @return The count of inputs.
   */
  public int getInputsCount() {
    return inputs_.size();
  }
  /**
   * <pre>
   * Ordered text inputs. A request MUST contain at least one item. Empty
   * strings are invalid; whitespace is preserved and is not normalized.
   * </pre>
   *
   * <code>repeated string inputs = 1;</code>
   * @param index The index of the element to return.
   * @return The inputs at the given index.
   */
  public java.lang.String getInputs(int index) {
    return inputs_.get(index);
  }
  /**
   * <pre>
   * Ordered text inputs. A request MUST contain at least one item. Empty
   * strings are invalid; whitespace is preserved and is not normalized.
   * </pre>
   *
   * <code>repeated string inputs = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the inputs at the given index.
   */
  public com.google.protobuf.ByteString
      getInputsBytes(int index) {
    return inputs_.getByteString(index);
  }

  public static final int MODEL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object model_ = "";
  /**
   * <pre>
   * Optional provider-supported model selector. Omitted means the model
   * configured for the embeddings operation by the selected CapabilityBinding.
   * A provider MUST NOT substitute another operation's default model. This is
   * not a routing policy.
   * </pre>
   *
   * <code>optional string model = 2;</code>
   * @return Whether the model field is set.
   */
  @java.lang.Override
  public boolean hasModel() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Optional provider-supported model selector. Omitted means the model
   * configured for the embeddings operation by the selected CapabilityBinding.
   * A provider MUST NOT substitute another operation's default model. This is
   * not a routing policy.
   * </pre>
   *
   * <code>optional string model = 2;</code>
   * @return The model.
   */
  @java.lang.Override
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      model_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional provider-supported model selector. Omitted means the model
   * configured for the embeddings operation by the selected CapabilityBinding.
   * A provider MUST NOT substitute another operation's default model. This is
   * not a routing policy.
   * </pre>
   *
   * <code>optional string model = 2;</code>
   * @return The bytes for model.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < inputs_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, inputs_.getRaw(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, model_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < inputs_.size(); i++) {
        dataSize += computeStringSizeNoTag(inputs_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getInputsList().size();
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, model_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.cyrene.proto.model.provider.v1.EmbeddingsRequest)) {
      return super.equals(obj);
    }
    io.cyrene.proto.model.provider.v1.EmbeddingsRequest other = (io.cyrene.proto.model.provider.v1.EmbeddingsRequest) obj;

    if (!getInputsList()
        .equals(other.getInputsList())) return false;
    if (hasModel() != other.hasModel()) return false;
    if (hasModel()) {
      if (!getModel()
          .equals(other.getModel())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInputsCount() > 0) {
      hash = (37 * hash) + INPUTS_FIELD_NUMBER;
      hash = (53 * hash) + getInputsList().hashCode();
    }
    if (hasModel()) {
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.cyrene.proto.model.provider.v1.EmbeddingsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.model.provider.v1.EmbeddingsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.model.provider.v1.EmbeddingsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.model.provider.v1.EmbeddingsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.model.provider.v1.EmbeddingsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.model.provider.v1.EmbeddingsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.model.provider.v1.EmbeddingsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.model.provider.v1.EmbeddingsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.cyrene.proto.model.provider.v1.EmbeddingsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.cyrene.proto.model.provider.v1.EmbeddingsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.cyrene.proto.model.provider.v1.EmbeddingsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.model.provider.v1.EmbeddingsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.cyrene.proto.model.provider.v1.EmbeddingsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code cyrene.model.provider.v1.EmbeddingsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cyrene.model.provider.v1.EmbeddingsRequest)
      io.cyrene.proto.model.provider.v1.EmbeddingsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.cyrene.proto.model.provider.v1.ModelProviderProto.internal_static_cyrene_model_provider_v1_EmbeddingsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.cyrene.proto.model.provider.v1.ModelProviderProto.internal_static_cyrene_model_provider_v1_EmbeddingsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.cyrene.proto.model.provider.v1.EmbeddingsRequest.class, io.cyrene.proto.model.provider.v1.EmbeddingsRequest.Builder.class);
    }

    // Construct using io.cyrene.proto.model.provider.v1.EmbeddingsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      inputs_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      model_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.cyrene.proto.model.provider.v1.ModelProviderProto.internal_static_cyrene_model_provider_v1_EmbeddingsRequest_descriptor;
    }

    @java.lang.Override
    public io.cyrene.proto.model.provider.v1.EmbeddingsRequest getDefaultInstanceForType() {
      return io.cyrene.proto.model.provider.v1.EmbeddingsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.cyrene.proto.model.provider.v1.EmbeddingsRequest build() {
      io.cyrene.proto.model.provider.v1.EmbeddingsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.cyrene.proto.model.provider.v1.EmbeddingsRequest buildPartial() {
      io.cyrene.proto.model.provider.v1.EmbeddingsRequest result = new io.cyrene.proto.model.provider.v1.EmbeddingsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.cyrene.proto.model.provider.v1.EmbeddingsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        inputs_.makeImmutable();
        result.inputs_ = inputs_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.model_ = model_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.cyrene.proto.model.provider.v1.EmbeddingsRequest) {
        return mergeFrom((io.cyrene.proto.model.provider.v1.EmbeddingsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.cyrene.proto.model.provider.v1.EmbeddingsRequest other) {
      if (other == io.cyrene.proto.model.provider.v1.EmbeddingsRequest.getDefaultInstance()) return this;
      if (!other.inputs_.isEmpty()) {
        if (inputs_.isEmpty()) {
          inputs_ = other.inputs_;
          bitField0_ |= 0x00000001;
        } else {
          ensureInputsIsMutable();
          inputs_.addAll(other.inputs_);
        }
        onChanged();
      }
      if (other.hasModel()) {
        model_ = other.model_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureInputsIsMutable();
              inputs_.add(s);
              break;
            } // case 10
            case 18: {
              model_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList inputs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureInputsIsMutable() {
      if (!inputs_.isModifiable()) {
        inputs_ = new com.google.protobuf.LazyStringArrayList(inputs_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * Ordered text inputs. A request MUST contain at least one item. Empty
     * strings are invalid; whitespace is preserved and is not normalized.
     * </pre>
     *
     * <code>repeated string inputs = 1;</code>
     * @return A list containing the inputs.
     */
    public com.google.protobuf.ProtocolStringList
        getInputsList() {
      inputs_.makeImmutable();
      return inputs_;
    }
    /**
     * <pre>
     * Ordered text inputs. A request MUST contain at least one item. Empty
     * strings are invalid; whitespace is preserved and is not normalized.
     * </pre>
     *
     * <code>repeated string inputs = 1;</code>
     * @return The count of inputs.
     */
    public int getInputsCount() {
      return inputs_.size();
    }
    /**
     * <pre>
     * Ordered text inputs. A request MUST contain at least one item. Empty
     * strings are invalid; whitespace is preserved and is not normalized.
     * </pre>
     *
     * <code>repeated string inputs = 1;</code>
     * @param index The index of the element to return.
     * @return The inputs at the given index.
     */
    public java.lang.String getInputs(int index) {
      return inputs_.get(index);
    }
    /**
     * <pre>
     * Ordered text inputs. A request MUST contain at least one item. Empty
     * strings are invalid; whitespace is preserved and is not normalized.
     * </pre>
     *
     * <code>repeated string inputs = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the inputs at the given index.
     */
    public com.google.protobuf.ByteString
        getInputsBytes(int index) {
      return inputs_.getByteString(index);
    }
    /**
     * <pre>
     * Ordered text inputs. A request MUST contain at least one item. Empty
     * strings are invalid; whitespace is preserved and is not normalized.
     * </pre>
     *
     * <code>repeated string inputs = 1;</code>
     * @param index The index to set the value at.
     * @param value The inputs to set.
     * @return This builder for chaining.
     */
    public Builder setInputs(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureInputsIsMutable();
      inputs_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ordered text inputs. A request MUST contain at least one item. Empty
     * strings are invalid; whitespace is preserved and is not normalized.
     * </pre>
     *
     * <code>repeated string inputs = 1;</code>
     * @param value The inputs to add.
     * @return This builder for chaining.
     */
    public Builder addInputs(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureInputsIsMutable();
      inputs_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ordered text inputs. A request MUST contain at least one item. Empty
     * strings are invalid; whitespace is preserved and is not normalized.
     * </pre>
     *
     * <code>repeated string inputs = 1;</code>
     * @param values The inputs to add.
     * @return This builder for chaining.
     */
    public Builder addAllInputs(
        java.lang.Iterable<java.lang.String> values) {
      ensureInputsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, inputs_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ordered text inputs. A request MUST contain at least one item. Empty
     * strings are invalid; whitespace is preserved and is not normalized.
     * </pre>
     *
     * <code>repeated string inputs = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInputs() {
      inputs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ordered text inputs. A request MUST contain at least one item. Empty
     * strings are invalid; whitespace is preserved and is not normalized.
     * </pre>
     *
     * <code>repeated string inputs = 1;</code>
     * @param value The bytes of the inputs to add.
     * @return This builder for chaining.
     */
    public Builder addInputsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureInputsIsMutable();
      inputs_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object model_ = "";
    /**
     * <pre>
     * Optional provider-supported model selector. Omitted means the model
     * configured for the embeddings operation by the selected CapabilityBinding.
     * A provider MUST NOT substitute another operation's default model. This is
     * not a routing policy.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     * @return Whether the model field is set.
     */
    public boolean hasModel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Optional provider-supported model selector. Omitted means the model
     * configured for the embeddings operation by the selected CapabilityBinding.
     * A provider MUST NOT substitute another operation's default model. This is
     * not a routing policy.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     * @return The model.
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional provider-supported model selector. Omitted means the model
     * configured for the embeddings operation by the selected CapabilityBinding.
     * A provider MUST NOT substitute another operation's default model. This is
     * not a routing policy.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     * @return The bytes for model.
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional provider-supported model selector. Omitted means the model
     * configured for the embeddings operation by the selected CapabilityBinding.
     * A provider MUST NOT substitute another operation's default model. This is
     * not a routing policy.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     * @param value The model to set.
     * @return This builder for chaining.
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      model_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional provider-supported model selector. Omitted means the model
     * configured for the embeddings operation by the selected CapabilityBinding.
     * A provider MUST NOT substitute another operation's default model. This is
     * not a routing policy.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearModel() {
      model_ = getDefaultInstance().getModel();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional provider-supported model selector. Omitted means the model
     * configured for the embeddings operation by the selected CapabilityBinding.
     * A provider MUST NOT substitute another operation's default model. This is
     * not a routing policy.
     * </pre>
     *
     * <code>optional string model = 2;</code>
     * @param value The bytes for model to set.
     * @return This builder for chaining.
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      model_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cyrene.model.provider.v1.EmbeddingsRequest)
  }

  // @@protoc_insertion_point(class_scope:cyrene.model.provider.v1.EmbeddingsRequest)
  private static final io.cyrene.proto.model.provider.v1.EmbeddingsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.cyrene.proto.model.provider.v1.EmbeddingsRequest();
  }

  public static io.cyrene.proto.model.provider.v1.EmbeddingsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmbeddingsRequest>
      PARSER = new com.google.protobuf.AbstractParser<EmbeddingsRequest>() {
    @java.lang.Override
    public EmbeddingsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EmbeddingsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmbeddingsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.cyrene.proto.model.provider.v1.EmbeddingsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

