// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/memory/provider/v1/memory_provider.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.memory.provider.v1;

public interface ExportBatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cyrene.memory.provider.v1.ExportBatch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .cyrene.memory.provider.v1.MemoryItem items = 1;</code>
   */
  java.util.List<io.cyrene.proto.memory.provider.v1.MemoryItem> 
      getItemsList();
  /**
   * <code>repeated .cyrene.memory.provider.v1.MemoryItem items = 1;</code>
   */
  io.cyrene.proto.memory.provider.v1.MemoryItem getItems(int index);
  /**
   * <code>repeated .cyrene.memory.provider.v1.MemoryItem items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .cyrene.memory.provider.v1.MemoryItem items = 1;</code>
   */
  java.util.List<? extends io.cyrene.proto.memory.provider.v1.MemoryItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .cyrene.memory.provider.v1.MemoryItem items = 1;</code>
   */
  io.cyrene.proto.memory.provider.v1.MemoryItemOrBuilder getItemsOrBuilder(
      int index);
}
