// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyrene/memory/provider/v1/memory_provider.proto

// Protobuf Java Version: 3.25.3
package io.cyrene.proto.memory.provider.v1;

/**
 * <pre>
 * 3. Recall
 * </pre>
 *
 * Protobuf type {@code cyrene.memory.provider.v1.RecallMemoryRequest}
 */
public final class RecallMemoryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cyrene.memory.provider.v1.RecallMemoryRequest)
    RecallMemoryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecallMemoryRequest.newBuilder() to construct.
  private RecallMemoryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecallMemoryRequest() {
    tenantId_ = "";
    scope_ = "";
    subject_ = "";
    queryEmbedding_ = emptyFloatList();
    queryText_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RecallMemoryRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.cyrene.proto.memory.provider.v1.MemoryProviderProto.internal_static_cyrene_memory_provider_v1_RecallMemoryRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 6:
        return internalGetMetadataFilters();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.cyrene.proto.memory.provider.v1.MemoryProviderProto.internal_static_cyrene_memory_provider_v1_RecallMemoryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.cyrene.proto.memory.provider.v1.RecallMemoryRequest.class, io.cyrene.proto.memory.provider.v1.RecallMemoryRequest.Builder.class);
  }

  private int bitField0_;
  public static final int TENANT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <code>string tenant_id = 1;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <code>string tenant_id = 1;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCOPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object scope_ = "";
  /**
   * <code>optional string scope = 2;</code>
   * @return Whether the scope field is set.
   */
  @java.lang.Override
  public boolean hasScope() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string scope = 2;</code>
   * @return The scope.
   */
  @java.lang.Override
  public java.lang.String getScope() {
    java.lang.Object ref = scope_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scope_ = s;
      return s;
    }
  }
  /**
   * <code>optional string scope = 2;</code>
   * @return The bytes for scope.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScopeBytes() {
    java.lang.Object ref = scope_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scope_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUBJECT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object subject_ = "";
  /**
   * <code>optional string subject = 3;</code>
   * @return Whether the subject field is set.
   */
  @java.lang.Override
  public boolean hasSubject() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string subject = 3;</code>
   * @return The subject.
   */
  @java.lang.Override
  public java.lang.String getSubject() {
    java.lang.Object ref = subject_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subject_ = s;
      return s;
    }
  }
  /**
   * <code>optional string subject = 3;</code>
   * @return The bytes for subject.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubjectBytes() {
    java.lang.Object ref = subject_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subject_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUERY_EMBEDDING_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.FloatList queryEmbedding_ =
      emptyFloatList();
  /**
   * <code>repeated float query_embedding = 4;</code>
   * @return A list containing the queryEmbedding.
   */
  @java.lang.Override
  public java.util.List<java.lang.Float>
      getQueryEmbeddingList() {
    return queryEmbedding_;
  }
  /**
   * <code>repeated float query_embedding = 4;</code>
   * @return The count of queryEmbedding.
   */
  public int getQueryEmbeddingCount() {
    return queryEmbedding_.size();
  }
  /**
   * <code>repeated float query_embedding = 4;</code>
   * @param index The index of the element to return.
   * @return The queryEmbedding at the given index.
   */
  public float getQueryEmbedding(int index) {
    return queryEmbedding_.getFloat(index);
  }
  private int queryEmbeddingMemoizedSerializedSize = -1;

  public static final int QUERY_TEXT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object queryText_ = "";
  /**
   * <code>optional string query_text = 5;</code>
   * @return Whether the queryText field is set.
   */
  @java.lang.Override
  public boolean hasQueryText() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string query_text = 5;</code>
   * @return The queryText.
   */
  @java.lang.Override
  public java.lang.String getQueryText() {
    java.lang.Object ref = queryText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      queryText_ = s;
      return s;
    }
  }
  /**
   * <code>optional string query_text = 5;</code>
   * @return The bytes for queryText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQueryTextBytes() {
    java.lang.Object ref = queryText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      queryText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATA_FILTERS_FIELD_NUMBER = 6;
  private static final class MetadataFiltersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                io.cyrene.proto.memory.provider.v1.MemoryProviderProto.internal_static_cyrene_memory_provider_v1_RecallMemoryRequest_MetadataFiltersEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> metadataFilters_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMetadataFilters() {
    if (metadataFilters_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetadataFiltersDefaultEntryHolder.defaultEntry);
    }
    return metadataFilters_;
  }
  public int getMetadataFiltersCount() {
    return internalGetMetadataFilters().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; metadata_filters = 6;</code>
   */
  @java.lang.Override
  public boolean containsMetadataFilters(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMetadataFilters().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetadataFiltersMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMetadataFilters() {
    return getMetadataFiltersMap();
  }
  /**
   * <code>map&lt;string, string&gt; metadata_filters = 6;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getMetadataFiltersMap() {
    return internalGetMetadataFilters().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; metadata_filters = 6;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getMetadataFiltersOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetadataFilters().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; metadata_filters = 6;</code>
   */
  @java.lang.Override
  public java.lang.String getMetadataFiltersOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetadataFilters().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int MIN_SIMILARITY_FIELD_NUMBER = 7;
  private float minSimilarity_ = 0F;
  /**
   * <code>optional float min_similarity = 7;</code>
   * @return Whether the minSimilarity field is set.
   */
  @java.lang.Override
  public boolean hasMinSimilarity() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional float min_similarity = 7;</code>
   * @return The minSimilarity.
   */
  @java.lang.Override
  public float getMinSimilarity() {
    return minSimilarity_;
  }

  public static final int TOP_K_FIELD_NUMBER = 8;
  private int topK_ = 0;
  /**
   * <code>optional int32 top_k = 8;</code>
   * @return Whether the topK field is set.
   */
  @java.lang.Override
  public boolean hasTopK() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 top_k = 8;</code>
   * @return The topK.
   */
  @java.lang.Override
  public int getTopK() {
    return topK_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tenantId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, scope_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, subject_);
    }
    if (getQueryEmbeddingList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(queryEmbeddingMemoizedSerializedSize);
    }
    for (int i = 0; i < queryEmbedding_.size(); i++) {
      output.writeFloatNoTag(queryEmbedding_.getFloat(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, queryText_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetMetadataFilters(),
        MetadataFiltersDefaultEntryHolder.defaultEntry,
        6);
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeFloat(7, minSimilarity_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(8, topK_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tenantId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, scope_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, subject_);
    }
    {
      int dataSize = 0;
      dataSize = 4 * getQueryEmbeddingList().size();
      size += dataSize;
      if (!getQueryEmbeddingList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      queryEmbeddingMemoizedSerializedSize = dataSize;
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, queryText_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMetadataFilters().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      metadataFilters__ = MetadataFiltersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, metadataFilters__);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(7, minSimilarity_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, topK_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.cyrene.proto.memory.provider.v1.RecallMemoryRequest)) {
      return super.equals(obj);
    }
    io.cyrene.proto.memory.provider.v1.RecallMemoryRequest other = (io.cyrene.proto.memory.provider.v1.RecallMemoryRequest) obj;

    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (hasScope() != other.hasScope()) return false;
    if (hasScope()) {
      if (!getScope()
          .equals(other.getScope())) return false;
    }
    if (hasSubject() != other.hasSubject()) return false;
    if (hasSubject()) {
      if (!getSubject()
          .equals(other.getSubject())) return false;
    }
    if (!getQueryEmbeddingList()
        .equals(other.getQueryEmbeddingList())) return false;
    if (hasQueryText() != other.hasQueryText()) return false;
    if (hasQueryText()) {
      if (!getQueryText()
          .equals(other.getQueryText())) return false;
    }
    if (!internalGetMetadataFilters().equals(
        other.internalGetMetadataFilters())) return false;
    if (hasMinSimilarity() != other.hasMinSimilarity()) return false;
    if (hasMinSimilarity()) {
      if (java.lang.Float.floatToIntBits(getMinSimilarity())
          != java.lang.Float.floatToIntBits(
              other.getMinSimilarity())) return false;
    }
    if (hasTopK() != other.hasTopK()) return false;
    if (hasTopK()) {
      if (getTopK()
          != other.getTopK()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    if (hasScope()) {
      hash = (37 * hash) + SCOPE_FIELD_NUMBER;
      hash = (53 * hash) + getScope().hashCode();
    }
    if (hasSubject()) {
      hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getSubject().hashCode();
    }
    if (getQueryEmbeddingCount() > 0) {
      hash = (37 * hash) + QUERY_EMBEDDING_FIELD_NUMBER;
      hash = (53 * hash) + getQueryEmbeddingList().hashCode();
    }
    if (hasQueryText()) {
      hash = (37 * hash) + QUERY_TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getQueryText().hashCode();
    }
    if (!internalGetMetadataFilters().getMap().isEmpty()) {
      hash = (37 * hash) + METADATA_FILTERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMetadataFilters().hashCode();
    }
    if (hasMinSimilarity()) {
      hash = (37 * hash) + MIN_SIMILARITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMinSimilarity());
    }
    if (hasTopK()) {
      hash = (37 * hash) + TOP_K_FIELD_NUMBER;
      hash = (53 * hash) + getTopK();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.cyrene.proto.memory.provider.v1.RecallMemoryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.memory.provider.v1.RecallMemoryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.memory.provider.v1.RecallMemoryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.memory.provider.v1.RecallMemoryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.memory.provider.v1.RecallMemoryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.cyrene.proto.memory.provider.v1.RecallMemoryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.cyrene.proto.memory.provider.v1.RecallMemoryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.memory.provider.v1.RecallMemoryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.cyrene.proto.memory.provider.v1.RecallMemoryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.cyrene.proto.memory.provider.v1.RecallMemoryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.cyrene.proto.memory.provider.v1.RecallMemoryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.cyrene.proto.memory.provider.v1.RecallMemoryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.cyrene.proto.memory.provider.v1.RecallMemoryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 3. Recall
   * </pre>
   *
   * Protobuf type {@code cyrene.memory.provider.v1.RecallMemoryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cyrene.memory.provider.v1.RecallMemoryRequest)
      io.cyrene.proto.memory.provider.v1.RecallMemoryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.cyrene.proto.memory.provider.v1.MemoryProviderProto.internal_static_cyrene_memory_provider_v1_RecallMemoryRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 6:
          return internalGetMetadataFilters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableMetadataFilters();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.cyrene.proto.memory.provider.v1.MemoryProviderProto.internal_static_cyrene_memory_provider_v1_RecallMemoryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.cyrene.proto.memory.provider.v1.RecallMemoryRequest.class, io.cyrene.proto.memory.provider.v1.RecallMemoryRequest.Builder.class);
    }

    // Construct using io.cyrene.proto.memory.provider.v1.RecallMemoryRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tenantId_ = "";
      scope_ = "";
      subject_ = "";
      queryEmbedding_ = emptyFloatList();
      queryText_ = "";
      internalGetMutableMetadataFilters().clear();
      minSimilarity_ = 0F;
      topK_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.cyrene.proto.memory.provider.v1.MemoryProviderProto.internal_static_cyrene_memory_provider_v1_RecallMemoryRequest_descriptor;
    }

    @java.lang.Override
    public io.cyrene.proto.memory.provider.v1.RecallMemoryRequest getDefaultInstanceForType() {
      return io.cyrene.proto.memory.provider.v1.RecallMemoryRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.cyrene.proto.memory.provider.v1.RecallMemoryRequest build() {
      io.cyrene.proto.memory.provider.v1.RecallMemoryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.cyrene.proto.memory.provider.v1.RecallMemoryRequest buildPartial() {
      io.cyrene.proto.memory.provider.v1.RecallMemoryRequest result = new io.cyrene.proto.memory.provider.v1.RecallMemoryRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.cyrene.proto.memory.provider.v1.RecallMemoryRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tenantId_ = tenantId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.scope_ = scope_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.subject_ = subject_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        queryEmbedding_.makeImmutable();
        result.queryEmbedding_ = queryEmbedding_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.queryText_ = queryText_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.metadataFilters_ = internalGetMetadataFilters();
        result.metadataFilters_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.minSimilarity_ = minSimilarity_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.topK_ = topK_;
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.cyrene.proto.memory.provider.v1.RecallMemoryRequest) {
        return mergeFrom((io.cyrene.proto.memory.provider.v1.RecallMemoryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.cyrene.proto.memory.provider.v1.RecallMemoryRequest other) {
      if (other == io.cyrene.proto.memory.provider.v1.RecallMemoryRequest.getDefaultInstance()) return this;
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasScope()) {
        scope_ = other.scope_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasSubject()) {
        subject_ = other.subject_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.queryEmbedding_.isEmpty()) {
        if (queryEmbedding_.isEmpty()) {
          queryEmbedding_ = other.queryEmbedding_;
          queryEmbedding_.makeImmutable();
          bitField0_ |= 0x00000008;
        } else {
          ensureQueryEmbeddingIsMutable();
          queryEmbedding_.addAll(other.queryEmbedding_);
        }
        onChanged();
      }
      if (other.hasQueryText()) {
        queryText_ = other.queryText_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      internalGetMutableMetadataFilters().mergeFrom(
          other.internalGetMetadataFilters());
      bitField0_ |= 0x00000020;
      if (other.hasMinSimilarity()) {
        setMinSimilarity(other.getMinSimilarity());
      }
      if (other.hasTopK()) {
        setTopK(other.getTopK());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              scope_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              subject_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 37: {
              float v = input.readFloat();
              ensureQueryEmbeddingIsMutable();
              queryEmbedding_.addFloat(v);
              break;
            } // case 37
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              int alloc = length > 4096 ? 4096 : length;
              ensureQueryEmbeddingIsMutable(alloc / 4);
              while (input.getBytesUntilLimit() > 0) {
                queryEmbedding_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            } // case 34
            case 42: {
              queryText_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              metadataFilters__ = input.readMessage(
                  MetadataFiltersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMetadataFilters().getMutableMap().put(
                  metadataFilters__.getKey(), metadataFilters__.getValue());
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 61: {
              minSimilarity_ = input.readFloat();
              bitField0_ |= 0x00000040;
              break;
            } // case 61
            case 64: {
              topK_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tenantId_ = "";
    /**
     * <code>string tenant_id = 1;</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tenant_id = 1;</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tenant_id = 1;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string tenant_id = 1;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object scope_ = "";
    /**
     * <code>optional string scope = 2;</code>
     * @return Whether the scope field is set.
     */
    public boolean hasScope() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string scope = 2;</code>
     * @return The scope.
     */
    public java.lang.String getScope() {
      java.lang.Object ref = scope_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scope_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string scope = 2;</code>
     * @return The bytes for scope.
     */
    public com.google.protobuf.ByteString
        getScopeBytes() {
      java.lang.Object ref = scope_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scope_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string scope = 2;</code>
     * @param value The scope to set.
     * @return This builder for chaining.
     */
    public Builder setScope(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      scope_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string scope = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearScope() {
      scope_ = getDefaultInstance().getScope();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string scope = 2;</code>
     * @param value The bytes for scope to set.
     * @return This builder for chaining.
     */
    public Builder setScopeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      scope_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object subject_ = "";
    /**
     * <code>optional string subject = 3;</code>
     * @return Whether the subject field is set.
     */
    public boolean hasSubject() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string subject = 3;</code>
     * @return The subject.
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string subject = 3;</code>
     * @return The bytes for subject.
     */
    public com.google.protobuf.ByteString
        getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string subject = 3;</code>
     * @param value The subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubject(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      subject_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string subject = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubject() {
      subject_ = getDefaultInstance().getSubject();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string subject = 3;</code>
     * @param value The bytes for subject to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      subject_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.FloatList queryEmbedding_ = emptyFloatList();
    private void ensureQueryEmbeddingIsMutable() {
      if (!queryEmbedding_.isModifiable()) {
        queryEmbedding_ = makeMutableCopy(queryEmbedding_);
      }
      bitField0_ |= 0x00000008;
    }
    private void ensureQueryEmbeddingIsMutable(int capacity) {
      if (!queryEmbedding_.isModifiable()) {
        queryEmbedding_ = makeMutableCopy(queryEmbedding_, capacity);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated float query_embedding = 4;</code>
     * @return A list containing the queryEmbedding.
     */
    public java.util.List<java.lang.Float>
        getQueryEmbeddingList() {
      queryEmbedding_.makeImmutable();
      return queryEmbedding_;
    }
    /**
     * <code>repeated float query_embedding = 4;</code>
     * @return The count of queryEmbedding.
     */
    public int getQueryEmbeddingCount() {
      return queryEmbedding_.size();
    }
    /**
     * <code>repeated float query_embedding = 4;</code>
     * @param index The index of the element to return.
     * @return The queryEmbedding at the given index.
     */
    public float getQueryEmbedding(int index) {
      return queryEmbedding_.getFloat(index);
    }
    /**
     * <code>repeated float query_embedding = 4;</code>
     * @param index The index to set the value at.
     * @param value The queryEmbedding to set.
     * @return This builder for chaining.
     */
    public Builder setQueryEmbedding(
        int index, float value) {

      ensureQueryEmbeddingIsMutable();
      queryEmbedding_.setFloat(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float query_embedding = 4;</code>
     * @param value The queryEmbedding to add.
     * @return This builder for chaining.
     */
    public Builder addQueryEmbedding(float value) {

      ensureQueryEmbeddingIsMutable();
      queryEmbedding_.addFloat(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float query_embedding = 4;</code>
     * @param values The queryEmbedding to add.
     * @return This builder for chaining.
     */
    public Builder addAllQueryEmbedding(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureQueryEmbeddingIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, queryEmbedding_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated float query_embedding = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueryEmbedding() {
      queryEmbedding_ = emptyFloatList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private java.lang.Object queryText_ = "";
    /**
     * <code>optional string query_text = 5;</code>
     * @return Whether the queryText field is set.
     */
    public boolean hasQueryText() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string query_text = 5;</code>
     * @return The queryText.
     */
    public java.lang.String getQueryText() {
      java.lang.Object ref = queryText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        queryText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string query_text = 5;</code>
     * @return The bytes for queryText.
     */
    public com.google.protobuf.ByteString
        getQueryTextBytes() {
      java.lang.Object ref = queryText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queryText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string query_text = 5;</code>
     * @param value The queryText to set.
     * @return This builder for chaining.
     */
    public Builder setQueryText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      queryText_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional string query_text = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearQueryText() {
      queryText_ = getDefaultInstance().getQueryText();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>optional string query_text = 5;</code>
     * @param value The bytes for queryText to set.
     * @return This builder for chaining.
     */
    public Builder setQueryTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      queryText_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metadataFilters_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMetadataFilters() {
      if (metadataFilters_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetadataFiltersDefaultEntryHolder.defaultEntry);
      }
      return metadataFilters_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableMetadataFilters() {
      if (metadataFilters_ == null) {
        metadataFilters_ = com.google.protobuf.MapField.newMapField(
            MetadataFiltersDefaultEntryHolder.defaultEntry);
      }
      if (!metadataFilters_.isMutable()) {
        metadataFilters_ = metadataFilters_.copy();
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return metadataFilters_;
    }
    public int getMetadataFiltersCount() {
      return internalGetMetadataFilters().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; metadata_filters = 6;</code>
     */
    @java.lang.Override
    public boolean containsMetadataFilters(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMetadataFilters().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetadataFiltersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetadataFilters() {
      return getMetadataFiltersMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata_filters = 6;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getMetadataFiltersMap() {
      return internalGetMetadataFilters().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata_filters = 6;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getMetadataFiltersOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadataFilters().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; metadata_filters = 6;</code>
     */
    @java.lang.Override
    public java.lang.String getMetadataFiltersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadataFilters().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearMetadataFilters() {
      bitField0_ = (bitField0_ & ~0x00000020);
      internalGetMutableMetadataFilters().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; metadata_filters = 6;</code>
     */
    public Builder removeMetadataFilters(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMetadataFilters().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableMetadataFilters() {
      bitField0_ |= 0x00000020;
      return internalGetMutableMetadataFilters().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata_filters = 6;</code>
     */
    public Builder putMetadataFilters(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableMetadataFilters().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; metadata_filters = 6;</code>
     */
    public Builder putAllMetadataFilters(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMetadataFilters().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000020;
      return this;
    }

    private float minSimilarity_ ;
    /**
     * <code>optional float min_similarity = 7;</code>
     * @return Whether the minSimilarity field is set.
     */
    @java.lang.Override
    public boolean hasMinSimilarity() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional float min_similarity = 7;</code>
     * @return The minSimilarity.
     */
    @java.lang.Override
    public float getMinSimilarity() {
      return minSimilarity_;
    }
    /**
     * <code>optional float min_similarity = 7;</code>
     * @param value The minSimilarity to set.
     * @return This builder for chaining.
     */
    public Builder setMinSimilarity(float value) {

      minSimilarity_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional float min_similarity = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinSimilarity() {
      bitField0_ = (bitField0_ & ~0x00000040);
      minSimilarity_ = 0F;
      onChanged();
      return this;
    }

    private int topK_ ;
    /**
     * <code>optional int32 top_k = 8;</code>
     * @return Whether the topK field is set.
     */
    @java.lang.Override
    public boolean hasTopK() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int32 top_k = 8;</code>
     * @return The topK.
     */
    @java.lang.Override
    public int getTopK() {
      return topK_;
    }
    /**
     * <code>optional int32 top_k = 8;</code>
     * @param value The topK to set.
     * @return This builder for chaining.
     */
    public Builder setTopK(int value) {

      topK_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 top_k = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopK() {
      bitField0_ = (bitField0_ & ~0x00000080);
      topK_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cyrene.memory.provider.v1.RecallMemoryRequest)
  }

  // @@protoc_insertion_point(class_scope:cyrene.memory.provider.v1.RecallMemoryRequest)
  private static final io.cyrene.proto.memory.provider.v1.RecallMemoryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.cyrene.proto.memory.provider.v1.RecallMemoryRequest();
  }

  public static io.cyrene.proto.memory.provider.v1.RecallMemoryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecallMemoryRequest>
      PARSER = new com.google.protobuf.AbstractParser<RecallMemoryRequest>() {
    @java.lang.Override
    public RecallMemoryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RecallMemoryRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecallMemoryRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.cyrene.proto.memory.provider.v1.RecallMemoryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

